In [26]:
from utils import *
from heuristique_glouton import *
from heuristique_itérative import *
from evaluation import *
from Lin_prog import *

In [27]:
df_ville,df_object,capacity=parse_ttp_file("a280_n279_bounded-strongly-corr_01.ttp")

In [28]:
df_ville

       X    Y
1    288  149
2    288  129
3    270  133
4    256  141
5    256  157
..   ...  ...
276  236  145
277  246  141
278  252  125
279  260  129
280  280  133

[280 rows x 2 columns]

In [29]:
df_object

     Profit  Weight  City_Index
1       101       1           2
2       202       2           3
3       404       4           4
4       202       2           5
5       996     896           6
..      ...     ...         ...
275     786     686         276
276    1572    1372         277
277     786     686         278
278     566     466         279
279     456     356         280

[279 rows x 3 columns]

In [30]:
pi,obj_pris,poids_tot,dict_ville_objet_pris=algo_glouton(df_ville,df_object,capacity)

Loading:  96%|█████████▌| 24949/25936 [00:11<00:00, 2256.41weight unit/s, Current Weight=24949, Nb_ville=254]

In [31]:
for ville in pi:
    print("Dans la ville ",ville," le voleur prend ",len(dict_ville_objet_pris[ville])," objet(s).")

Dans la ville  1  le voleur prend  0  objet(s).
Dans la ville  6  le voleur prend  0  objet(s).
Dans la ville  7  le voleur prend  0  objet(s).
Dans la ville  178  le voleur prend  0  objet(s).
Dans la ville  99  le voleur prend  0  objet(s).
Dans la ville  96  le voleur prend  0  objet(s).
Dans la ville  97  le voleur prend  0  objet(s).
Dans la ville  98  le voleur prend  0  objet(s).
Dans la ville  93  le voleur prend  0  objet(s).
Dans la ville  94  le voleur prend  0  objet(s).
Dans la ville  95  le voleur prend  0  objet(s).
Dans la ville  76  le voleur prend  0  objet(s).
Dans la ville  117  le voleur prend  0  objet(s).
Dans la ville  115  le voleur prend  0  objet(s).
Dans la ville  116  le voleur prend  0  objet(s).
Dans la ville  64  le voleur prend  0  objet(s).
Dans la ville  56  le voleur prend  0  objet(s).
Dans la ville  55  le voleur prend  0  objet(s).
Dans la ville  54  le voleur prend  0  objet(s).
Dans la ville  53  le voleur prend  0  objet(s).
Dans la ville  38  le voleur prend  0  objet(s).
Dans la ville  39  le voleur prend  0  objet(s).
Dans la ville  40  le voleur prend  0  objet(s).
Dans la ville  41  le voleur prend  0  objet(s).
Dans la ville  42  le voleur prend  0  objet(s).
Dans la ville  43  le voleur prend  0  objet(s).
Dans la ville  60  le voleur prend  1  objet(s).
Dans la ville  61  le voleur prend  0  objet(s).
Dans la ville  118  le voleur prend  0  objet(s).
Dans la ville  62  le voleur prend  0  objet(s).
Dans la ville  63  le voleur prend  0  objet(s).
Dans la ville  59  le voleur prend  0  objet(s).
Dans la ville  58  le voleur prend  0  objet(s).
Dans la ville  57  le voleur prend  0  objet(s).
Dans la ville  44  le voleur prend  1  objet(s).
Dans la ville  45  le voleur prend  0  objet(s).
Dans la ville  46  le voleur prend  0  objet(s).
Dans la ville  47  le voleur prend  0  objet(s).
Dans la ville  48  le voleur prend  0  objet(s).
Dans la ville  49  le voleur prend  0  objet(s).
Dans la ville  52  le voleur prend  1  objet(s).
Dans la ville  51  le voleur prend  1  objet(s).
Dans la ville  50  le voleur prend  1  objet(s).
Dans la ville  37  le voleur prend  1  objet(s).
Dans la ville  36  le voleur prend  0  objet(s).
Dans la ville  35  le voleur prend  0  objet(s).
Dans la ville  34  le voleur prend  1  objet(s).
Dans la ville  33  le voleur prend  0  objet(s).
Dans la ville  32  le voleur prend  0  objet(s).
Dans la ville  30  le voleur prend  1  objet(s).
Dans la ville  31  le voleur prend  0  objet(s).
Dans la ville  29  le voleur prend  0  objet(s).
Dans la ville  28  le voleur prend  0  objet(s).
Dans la ville  27  le voleur prend  0  objet(s).
Dans la ville  26  le voleur prend  0  objet(s).
Dans la ville  22  le voleur prend  1  objet(s).
Dans la ville  25  le voleur prend  0  objet(s).
Dans la ville  23  le voleur prend  0  objet(s).
Dans la ville  24  le voleur prend  0  objet(s).
Dans la ville  14  le voleur prend  0  objet(s).
Dans la ville  15  le voleur prend  0  objet(s).
Dans la ville  13  le voleur prend  0  objet(s).
Dans la ville  12  le voleur prend  0  objet(s).
Dans la ville  11  le voleur prend  0  objet(s).
Dans la ville  10  le voleur prend  1  objet(s).
Dans la ville  8  le voleur prend  0  objet(s).
Dans la ville  9  le voleur prend  1  objet(s).
Dans la ville  259  le voleur prend  0  objet(s).
Dans la ville  260  le voleur prend  0  objet(s).
Dans la ville  261  le voleur prend  0  objet(s).
Dans la ville  262  le voleur prend  0  objet(s).
Dans la ville  270  le voleur prend  0  objet(s).
Dans la ville  269  le voleur prend  0  objet(s).
Dans la ville  135  le voleur prend  0  objet(s).
Dans la ville  134  le voleur prend  0  objet(s).
Dans la ville  133  le voleur prend  1  objet(s).
Dans la ville  18  le voleur prend  0  objet(s).
Dans la ville  17  le voleur prend  0  objet(s).
Dans la ville  16  le voleur prend  0  objet(s).
Dans la ville  271  le voleur prend  0  objet(s).
Dans la ville  272  le voleur prend  0  objet(s).
Dans la ville  273  le voleur prend  0  objet(s).
Dans la ville  274  le voleur prend  0  objet(s).
Dans la ville  275  le voleur prend  0  objet(s).
Dans la ville  276  le voleur prend  0  objet(s).
Dans la ville  277  le voleur prend  0  objet(s).
Dans la ville  242  le voleur prend  0  objet(s).
Dans la ville  243  le voleur prend  0  objet(s).
Dans la ville  280  le voleur prend  1  objet(s).
Dans la ville  279  le voleur prend  0  objet(s).
Dans la ville  278  le voleur prend  0  objet(s).
Dans la ville  248  le voleur prend  0  objet(s).
Dans la ville  247  le voleur prend  0  objet(s).
Dans la ville  238  le voleur prend  0  objet(s).
Dans la ville  239  le voleur prend  0  objet(s).
Dans la ville  240  le voleur prend  0  objet(s).
Dans la ville  241  le voleur prend  0  objet(s).
Dans la ville  244  le voleur prend  0  objet(s).
Dans la ville  245  le voleur prend  0  objet(s).
Dans la ville  246  le voleur prend  0  objet(s).
Dans la ville  231  le voleur prend  0  objet(s).
Dans la ville  233  le voleur prend  0  objet(s).
Dans la ville  232  le voleur prend  0  objet(s).
Dans la ville  237  le voleur prend  0  objet(s).
Dans la ville  236  le voleur prend  0  objet(s).
Dans la ville  235  le voleur prend  0  objet(s).
Dans la ville  234  le voleur prend  0  objet(s).
Dans la ville  218  le voleur prend  0  objet(s).
Dans la ville  219  le voleur prend  0  objet(s).
Dans la ville  223  le voleur prend  1  objet(s).
Dans la ville  224  le voleur prend  1  objet(s).
Dans la ville  225  le voleur prend  1  objet(s).
Dans la ville  226  le voleur prend  1  objet(s).
Dans la ville  227  le voleur prend  0  objet(s).
Dans la ville  228  le voleur prend  0  objet(s).
Dans la ville  229  le voleur prend  0  objet(s).
Dans la ville  230  le voleur prend  0  objet(s).
Dans la ville  251  le voleur prend  0  objet(s).
Dans la ville  250  le voleur prend  0  objet(s).
Dans la ville  249  le voleur prend  0  objet(s).
Dans la ville  252  le voleur prend  0  objet(s).
Dans la ville  253  le voleur prend  0  objet(s).
Dans la ville  254  le voleur prend  0  objet(s).
Dans la ville  255  le voleur prend  0  objet(s).
Dans la ville  256  le voleur prend  1  objet(s).
Dans la ville  257  le voleur prend  1  objet(s).
Dans la ville  258  le voleur prend  1  objet(s).
Dans la ville  263  le voleur prend  0  objet(s).
Dans la ville  264  le voleur prend  0  objet(s).
Dans la ville  265  le voleur prend  0  objet(s).
Dans la ville  149  le voleur prend  0  objet(s).
Dans la ville  150  le voleur prend  1  objet(s).
Dans la ville  179  le voleur prend  0  objet(s).
Dans la ville  180  le voleur prend  0  objet(s).
Dans la ville  186  le voleur prend  0  objet(s).
Dans la ville  184  le voleur prend  0  objet(s).
Dans la ville  174  le voleur prend  0  objet(s).
Dans la ville  173  le voleur prend  0  objet(s).
Dans la ville  106  le voleur prend  0  objet(s).
Dans la ville  105  le voleur prend  1  objet(s).
Dans la ville  104  le voleur prend  0  objet(s).
Dans la ville  103  le voleur prend  0  objet(s).
Dans la ville  169  le voleur prend  0  objet(s).
Dans la ville  170  le voleur prend  0  objet(s).
Dans la ville  171  le voleur prend  0  objet(s).
Dans la ville  172  le voleur prend  0  objet(s).
Dans la ville  166  le voleur prend  0  objet(s).
Dans la ville  167  le voleur prend  1  objet(s).
Dans la ville  168  le voleur prend  1  objet(s).
Dans la ville  100  le voleur prend  0  objet(s).
Dans la ville  101  le voleur prend  0  objet(s).
Dans la ville  102  le voleur prend  1  objet(s).
Dans la ville  92  le voleur prend  1  objet(s).
Dans la ville  91  le voleur prend  0  objet(s).
Dans la ville  90  le voleur prend  0  objet(s).
Dans la ville  112  le voleur prend  0  objet(s).
Dans la ville  110  le voleur prend  0  objet(s).
Dans la ville  111  le voleur prend  0  objet(s).
Dans la ville  114  le voleur prend  0  objet(s).
Dans la ville  113  le voleur prend  0  objet(s).
Dans la ville  84  le voleur prend  0  objet(s).
Dans la ville  83  le voleur prend  0  objet(s).
Dans la ville  82  le voleur prend  0  objet(s).
Dans la ville  81  le voleur prend  0  objet(s).
Dans la ville  80  le voleur prend  0  objet(s).
Dans la ville  79  le voleur prend  0  objet(s).
Dans la ville  78  le voleur prend  0  objet(s).
Dans la ville  77  le voleur prend  0  objet(s).
Dans la ville  75  le voleur prend  0  objet(s).
Dans la ville  74  le voleur prend  0  objet(s).
Dans la ville  73  le voleur prend  0  objet(s).
Dans la ville  72  le voleur prend  0  objet(s).
Dans la ville  71  le voleur prend  0  objet(s).
Dans la ville  70  le voleur prend  0  objet(s).
Dans la ville  69  le voleur prend  1  objet(s).
Dans la ville  68  le voleur prend  1  objet(s).
Dans la ville  67  le voleur prend  1  objet(s).
Dans la ville  66  le voleur prend  1  objet(s).
Dans la ville  65  le voleur prend  0  objet(s).
Dans la ville  85  le voleur prend  1  objet(s).
Dans la ville  86  le voleur prend  1  objet(s).
Dans la ville  87  le voleur prend  1  objet(s).
Dans la ville  88  le voleur prend  1  objet(s).
Dans la ville  89  le voleur prend  0  objet(s).
Dans la ville  109  le voleur prend  1  objet(s).
Dans la ville  108  le voleur prend  1  objet(s).
Dans la ville  107  le voleur prend  1  objet(s).
Dans la ville  165  le voleur prend  0  objet(s).
Dans la ville  164  le voleur prend  0  objet(s).
Dans la ville  163  le voleur prend  0  objet(s).
Dans la ville  162  le voleur prend  0  objet(s).
Dans la ville  161  le voleur prend  0  objet(s).
Dans la ville  175  le voleur prend  0  objet(s).
Dans la ville  160  le voleur prend  0  objet(s).
Dans la ville  159  le voleur prend  1  objet(s).
Dans la ville  158  le voleur prend  1  objet(s).
Dans la ville  157  le voleur prend  0  objet(s).
Dans la ville  119  le voleur prend  0  objet(s).
Dans la ville  120  le voleur prend  0  objet(s).
Dans la ville  121  le voleur prend  0  objet(s).
Dans la ville  122  le voleur prend  0  objet(s).
Dans la ville  123  le voleur prend  0  objet(s).
Dans la ville  124  le voleur prend  0  objet(s).
Dans la ville  125  le voleur prend  0  objet(s).
Dans la ville  126  le voleur prend  1  objet(s).
Dans la ville  127  le voleur prend  1  objet(s).
Dans la ville  130  le voleur prend  0  objet(s).
Dans la ville  131  le voleur prend  0  objet(s).
Dans la ville  132  le voleur prend  0  objet(s).
Dans la ville  19  le voleur prend  1  objet(s).
Dans la ville  20  le voleur prend  1  objet(s).
Dans la ville  21  le voleur prend  1  objet(s).
Dans la ville  128  le voleur prend  1  objet(s).
Dans la ville  129  le voleur prend  1  objet(s).
Dans la ville  154  le voleur prend  0  objet(s).
Dans la ville  155  le voleur prend  0  objet(s).
Dans la ville  153  le voleur prend  1  objet(s).
Dans la ville  156  le voleur prend  0  objet(s).
Dans la ville  152  le voleur prend  1  objet(s).
Dans la ville  151  le voleur prend  1  objet(s).
Dans la ville  177  le voleur prend  0  objet(s).
Dans la ville  176  le voleur prend  0  objet(s).
Dans la ville  181  le voleur prend  0  objet(s).
Dans la ville  182  le voleur prend  1  objet(s).
Dans la ville  183  le voleur prend  1  objet(s).
Dans la ville  185  le voleur prend  0  objet(s).
Dans la ville  187  le voleur prend  1  objet(s).
Dans la ville  188  le voleur prend  0  objet(s).
Dans la ville  189  le voleur prend  0  objet(s).
Dans la ville  190  le voleur prend  0  objet(s).
Dans la ville  191  le voleur prend  0  objet(s).
Dans la ville  192  le voleur prend  0  objet(s).
Dans la ville  193  le voleur prend  0  objet(s).
Dans la ville  196  le voleur prend  0  objet(s).
Dans la ville  195  le voleur prend  0  objet(s).
Dans la ville  194  le voleur prend  0  objet(s).
Dans la ville  197  le voleur prend  0  objet(s).
Dans la ville  198  le voleur prend  0  objet(s).
Dans la ville  199  le voleur prend  0  objet(s).
Dans la ville  145  le voleur prend  1  objet(s).
Dans la ville  146  le voleur prend  0  objet(s).
Dans la ville  147  le voleur prend  0  objet(s).
Dans la ville  148  le voleur prend  0  objet(s).
Dans la ville  139  le voleur prend  0  objet(s).
Dans la ville  138  le voleur prend  0  objet(s).
Dans la ville  137  le voleur prend  0  objet(s).
Dans la ville  136  le voleur prend  0  objet(s).
Dans la ville  268  le voleur prend  0  objet(s).
Dans la ville  267  le voleur prend  0  objet(s).
Dans la ville  266  le voleur prend  0  objet(s).
Dans la ville  140  le voleur prend  0  objet(s).
Dans la ville  141  le voleur prend  0  objet(s).
Dans la ville  142  le voleur prend  1  objet(s).
Dans la ville  143  le voleur prend  1  objet(s).
Dans la ville  144  le voleur prend  1  objet(s).
Dans la ville  200  le voleur prend  0  objet(s).
Dans la ville  201  le voleur prend  0  objet(s).
Dans la ville  202  le voleur prend  0  objet(s).
Dans la ville  203  le voleur prend  0  objet(s).
Dans la ville  204  le voleur prend  0  objet(s).
Dans la ville  205  le voleur prend  0  objet(s).
Dans la ville  206  le voleur prend  0  objet(s).
Dans la ville  207  le voleur prend  0  objet(s).
Dans la ville  208  le voleur prend  1  objet(s).
Dans la ville  209  le voleur prend  1  objet(s).
Dans la ville  210  le voleur prend  1  objet(s).
Dans la ville  211  le voleur prend  1  objet(s).
Dans la ville  212  le voleur prend  1  objet(s).
Dans la ville  213  le voleur prend  1  objet(s).
Dans la ville  214  le voleur prend  1  objet(s).
Dans la ville  215  le voleur prend  1  objet(s).
Dans la ville  216  le voleur prend  1  objet(s).
Dans la ville  217  le voleur prend  1  objet(s).
Dans la ville  220  le voleur prend  1  objet(s).
Dans la ville  221  le voleur prend  1  objet(s).
Dans la ville  222  le voleur prend  1  objet(s).
Dans la ville  5  le voleur prend  1  objet(s).
Dans la ville  4  le voleur prend  1  objet(s).
Dans la ville  3  le voleur prend  1  objet(s).
Dans la ville  2  le voleur prend  1  objet(s).

In [32]:
eval_non_lin(pi,df_ville,df_object,dict_ville_objet_pris,obj_pris,capacity)

yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
BENEFICE :  39249
COUT :  6840.9321285460655

(32408.067871453935, 39249, 6840.9321285460655)

In [33]:
eval_lin(pi,df_ville,df_object,dict_ville_objet_pris,obj_pris)

yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
BENEFICE :  39249
COUT :  31281285.950658288

(-31242036.950658288, 39249, 31281285.950658288)

In [34]:
prog_lin(df_ville,df_object,capacity)

Gurobi Optimizer version 12.0.0 build v12.0.0rc1 (win64 - Windows 10.0 (19045.2))

CPU model: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 78962 rows, 79519 columns and 468722 nonzeros
Model fingerprint: 0x25488a45
Model has 78118 quadratic objective terms
Variable types: 840 continuous, 78679 integer (78679 binary)
Coefficient statistics:
  Matrix range     [1e+00, 4e+03]
  Objective range  [1e+02, 4e+03]
  QObjective range [2e+01, 6e+02]
  Bounds range     [1e+00, 3e+02]
  RHS range        [1e+00, 3e+04]
Presolve removed 561 rows and 563 columns
Presolve time: 0.86s
Presolved: 156240 rows, 156795 columns, 623555 nonzeros
Variable types: 279 continuous, 156516 integer (78678 binary)
Deterministic concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Root barrier log...

Ordering time: 0.09s

Barrier statistics:
 Dense cols : 557
 AA' NZ     : 7.003e+05
 Factor NZ  : 1.634e+06 (roughly 140 MB of memory)
 Factor Ops : 4.707e+08 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -2.53008500e+10  5.50808084e+09  6.14e+04 9.09e-13  1.23e+06     6s
   1  -2.16563988e+10  8.89913587e+09  5.22e+04 3.84e+03  9.74e+05     6s
   2  -1.81874375e+10  1.04784677e+10  4.34e+04 1.11e+03  7.87e+05     7s
   3  -1.34023595e+10  1.20248615e+10  3.08e+04 1.79e+02  5.36e+05     7s
   4  -5.50629722e+09  1.20794720e+10  1.14e+04 1.48e-04  2.03e+05     8s
   5  -1.17931067e+09  7.42048769e+09  1.47e+03 2.66e-04  3.51e+04     8s
   6  -5.75747427e+08  1.33621112e+09  3.55e+02 1.01e-04  6.08e+03     9s
   7  -2.25067524e+08  2.62286912e+08  1.14e+02 3.23e-05  1.46e+03     9s
   8  -5.82594552e+07  6.82674332e+07  2.78e+01 5.77e-06  3.31e+02     9s
   9  -5.05024372e+06  5.23993959e+07  1.94e+00 4.08e-06  1.26e+02    10s
  10  -4.95863088e+05  1.18980579e+07  9.24e-14 8.09e-07  2.64e+01    10s
  11  -6.16393371e+04  4.23241800e+06  6.75e-14 2.58e-07  9.16e+00    10s
  12  -3.51019530e+04  2.20439225e+06  6.75e-14 1.36e-07  4.78e+00    11s
  13  -5.94542350e+03  1.78575899e+06  4.97e-14 1.10e-07  3.82e+00    11s
  14   3.05562875e+03  1.28803742e+06  3.91e-14 7.77e-08  2.74e+00    11s
  15   1.12193893e+04  8.67249566e+05  3.91e-14 5.01e-08  1.83e+00    11s
  16   1.77214898e+04  6.07955058e+05  3.55e-14 3.34e-08  1.26e+00    12s
  17   1.94650451e+04  4.80929915e+05  4.26e-14 2.56e-08  9.84e-01    12s
  18   2.13273415e+04  4.32214066e+05  2.84e-14 2.28e-08  8.76e-01    12s
  19   2.62695670e+04  3.35989312e+05  2.49e-14 1.68e-08  6.60e-01    13s
  20   2.81235228e+04  2.74147118e+05  2.31e-14 1.35e-08  5.25e-01    13s
  21   2.98353414e+04  2.20684271e+05  3.20e-14 1.05e-08  4.07e-01    13s
  22   3.23048434e+04  2.07313237e+05  4.26e-14 9.76e-09  3.73e-01    14s
  23   3.43055242e+04  1.87369467e+05  2.84e-14 8.69e-09  3.26e-01    14s
  24   3.48961970e+04  1.54531664e+05  3.55e-14 6.76e-09  2.55e-01    14s
  25   3.51655764e+04  1.27714921e+05  2.49e-14 5.23e-09  1.97e-01    14s
  26   3.62995210e+04  1.11649136e+05  2.84e-14 4.17e-09  1.61e-01    15s
  27   3.66735659e+04  1.08416084e+05  2.84e-14 3.98e-09  1.53e-01    15s
  28   3.75646370e+04  1.05713386e+05  2.13e-14 3.81e-09  1.45e-01    15s
  29   3.76368420e+04  9.56233301e+04  2.84e-14 3.19e-09  1.24e-01    15s
  30   3.79817316e+04  9.45094541e+04  2.13e-14 3.12e-09  1.21e-01    16s
  31   3.81797543e+04  9.26685536e+04  2.49e-14 3.01e-09  1.16e-01    16s
  32   3.83852509e+04  8.92613550e+04  3.55e-14 2.81e-09  1.08e-01    16s
  33   3.91163059e+04  8.50964802e+04  3.20e-14 2.55e-09  9.80e-02    16s
  34   3.93007776e+04  8.33883325e+04  2.84e-14 2.44e-09  9.40e-02    16s
  35   3.94127508e+04  8.05913712e+04  2.84e-14 2.28e-09  8.78e-02    17s
  36   3.95433959e+04  7.34682633e+04  3.55e-14 1.87e-09  7.23e-02    17s
  37   3.99245584e+04  7.11761208e+04  2.84e-14 1.74e-09  6.66e-02    17s
  38   3.99565162e+04  6.93361454e+04  2.13e-14 1.63e-09  6.26e-02    17s
  39   4.00252871e+04  6.89130728e+04  3.20e-14 1.60e-09  6.16e-02    18s
  40   4.02219825e+04  6.61171106e+04  3.55e-14 1.44e-09  5.52e-02    18s
  41   4.04678217e+04  6.18783998e+04  2.13e-14 1.18e-09  4.57e-02    18s
  42   4.11536388e+04  5.81548381e+04  2.84e-14 9.50e-10  3.63e-02    18s
  43   4.14370348e+04  5.52821801e+04  2.84e-14 7.81e-10  2.95e-02    19s
  44   4.15444558e+04  4.38377912e+04  3.55e-14 8.53e-11  4.89e-03    19s
  45   4.18945198e+04  4.22307327e+04  3.91e-14 2.14e-12  7.17e-04    19s
  46   4.20984786e+04  4.21581376e+04  4.26e-14 1.68e-12  1.27e-04    19s

Barrier performed 46 iterations in 19.37 seconds (10.05 work units)
Barrier solve interrupted - model solved by another algorithm

Concurrent spin time: 8.33s (can be avoided by choosing Method=3)

Solved with dual simplex

Root simplex log...

Iteration    Objective       Primal Inf.    Dual Inf.      Time
    5277    4.2123365e+04   0.000000e+00   0.000000e+00     19s

Root relaxation: objective 4.212336e+04, 5277 iterations, 15.12 seconds (6.00 work units)
Total elapsed time = 19.42s (DegenMoves)
Total elapsed time = 23.96s (DegenMoves)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 42123.3647    0 1585          - 42123.3647      -     -   25s
H    0     0                     101.0000000 42123.3647      -     -   28s
H    0     0                    10105.087464 42123.3647   317%     -   33s
H    0     0                    13205.773202 42123.3647   219%     -   33s
H    0     0                    14505.454967 42123.3647   190%     -   35s
H    0     0                    15246.629615 42123.3647   176%     -   35s
H    0     0                    21973.720800 42123.3647  91.7%     -   39s
H    0     0                    24836.435561 42123.3647  69.6%     -   39s
H    0     0                    24988.097599 42123.3647  68.6%     -   44s
H    0     0                    25013.404066 42123.3647  68.4%     -   51s
     0     0 27980.2319    0  709 25013.4041 27980.2319  11.9%     -   67s
     0     0 27977.5821    0  620 25013.4041 27977.5821  11.9%     -   85s
H    0     0                    25159.565646 27967.5113  11.2%     -  108s
     0     0 27967.2576    0  692 25159.5656 27967.2576  11.2%     -  112s
     0     0 27959.7502    0  611 25159.5656 27959.7502  11.1%     -  127s
H    0     0                    25295.081549 27958.5015  10.5%     -  207s
H    0     0                    25344.742221 27958.5015  10.3%     -  207s
     0     0 27958.5015    0  655 25344.7422 27958.5015  10.3%     -  210s
H    0     0                    26240.037559 27958.3537  6.55%     -  228s
     0     0 27958.3537    0  577 26240.0376 27958.3537  6.55%     -  252s
     0     0 27958.3537    0  564 26240.0376 27958.3537  6.55%     -  280s
     0     0 27958.3537    0  556 26240.0376 27958.3537  6.55%     -  303s
     0     0 27958.0399    0  556 26240.0376 27958.0399  6.55%     -  328s
H    0     0                    26787.194535 27957.9571  4.37%     -  336s
     0     0 27955.4607    0  541 26787.1945 27955.4607  4.36%     -  377s
     0     0 27955.2406    0  532 26787.1945 27955.2406  4.36%     -  408s
     0     0 27954.8552    0  126 26787.1945 27954.8552  4.36%     -  464s
     0     2 27954.8108    0  104 26787.1945 27954.8108  4.36%     -  520s
     7     9 27934.3262    3 1167 26787.1945 27947.6909  4.33%  2409  572s
     8    13 27910.0778    4  762 26787.1945 27947.6909  4.33%  2451  595s
    12    17 27866.0071    5  761 26787.1945 27942.5320  4.31%  4317  612s
H   36    41                    27545.834443 27942.5320  1.44%  2251  620s
    59    71 27818.1117   14  671 27545.8344 27942.5320  1.44%  1441  625s
    85    93 27797.8647   20  653 27545.8344 27942.5320  1.44%  1040  631s
   107   104 27750.6205   24  572 27545.8344 27942.5320  1.44%   861  636s
H  111   108                    27619.025090 27942.5320  1.17%   837  661s
   123   122 27750.6205   25  540 27619.0251 27942.5320  1.17%   790  666s
H  143   138                    27625.652507 27942.5320  1.15%   695  674s
   148   147 27750.6205   30  507 27625.6525 27942.5320  1.15%   673  676s
   173   167 27750.6205   34  469 27625.6525 27942.5320  1.15%   596  680s
   194   192 27750.6205   37  469 27625.6525 27942.5320  1.15%   550  685s
   208   199 27750.6205   38  462 27625.6525 27942.5320  1.15%   526  693s
H  209   199                    27632.279924 27942.5320  1.12%   524  693s
   215   209 27750.6205   39  446 27632.2799 27942.5320  1.12%   516  695s
   241   233 27750.6205   43  434 27632.2799 27942.5320  1.12%   485  700s
   263   256 27750.6205   47  494 27632.2799 27942.5320  1.12%   472  706s
   283   276 27750.6205   51  478 27632.2799 27942.5320  1.12%   467  712s
   296   296 27750.6205   54  503 27632.2799 27942.5320  1.12%   461  716s
   316   304 27750.6205   58  491 27632.2799 27942.5320  1.12%   447  720s
   338   333 27750.6205   61  484 27632.2799 27942.5320  1.12%   446  728s
   357   341 27750.6205   64  483 27632.2799 27942.5320  1.12%   444  743s
H  361   335                    27663.450254 27942.5320  1.01%   441  743s
   365   346 27750.6205   66  477 27663.4503 27942.5320  1.01%   443  747s
   376   351 27750.6205   69  480 27663.4503 27942.5320  1.01%   452  768s
   383   366 27750.6205   70  501 27663.4503 27942.5320  1.01%   451  773s
   400   385 27750.6205   74  487 27663.4503 27942.5320  1.01%   450  778s
   421   410 27750.6205   77  512 27663.4503 27942.5320  1.01%   449  784s
   446   438 27750.6205   85  474 27663.4503 27942.5320  1.01%   443  788s
   474   455 infeasible   90      27663.4503 27942.5320  1.01%   433  793s
   493   485 27717.7515   92  446 27663.4503 27942.5320  1.01%   433  798s
   523   516 27717.7515   98  451 27663.4503 27942.5320  1.01%   425  804s
   554   548 27717.7515  105  457 27663.4503 27942.5320  1.01%   417  810s
   586   581 27717.7515  109  470 27663.4503 27942.5320  1.01%   411  816s
   619   615 27717.7515  114  461 27663.4503 27942.5320  1.01%   404  823s
   655   644 27717.7515  121  459 27663.4503 27942.5320  1.01%   397  830s
   688   674 27717.7515  128  412 27663.4503 27942.5320  1.01%   396  838s
   718   714 27717.7515  135  460 27663.4503 27942.5320  1.01%   397  845s
   760   727 27717.7515  142  414 27663.4503 27942.5320  1.01%   387  857s
H  774   241                    27882.779816 27942.5320  0.21%   385  857s
   775   211     cutoff  142      27882.7798 27942.5320  0.21%   387  865s
   810   211 infeasible    6      27882.7798 27936.5749  0.19%   394  874s
   828   201 27887.5313   10  607 27882.7798 27936.5749  0.19%   411  882s
   850   116 27913.8228   99 37497 27882.7798 27930.8022  0.17%   416  951s
   852   117 27923.8748    6 1271 27882.7798 27930.8022  0.17%   415 1049s
   853   118 27913.8228   67  525 27882.7798 27930.8022  0.17%   414 1076s
   854   119 27913.8228   82  494 27882.7798 27930.8022  0.17%   414 1093s
   855   119 27913.8228   78  537 27882.7798 27930.8022  0.17%   413 1100s
   856   120 27884.3031    8  521 27882.7798 27930.8022  0.17%   413 1114s
   857   121 27913.8228   69  461 27882.7798 27929.7152  0.17%   412 1130s
   858   121 27913.8228   71  486 27882.7798 27929.7152  0.17%   412 1141s
   859   122 27913.8228  104  486 27882.7798 27929.7152  0.17%   411 1154s
   860   123 27913.8228   91  464 27882.7798 27928.7657  0.16%   411 1166s
   861   123 27884.3031    8  461 27882.7798 27928.7216  0.16%   410 1172s
   862   124 27920.1550    6  415 27882.7798 27928.0048  0.16%   410 1178s
   863   125 27913.8228   65  442 27882.7798 27925.2087  0.15%   409 1181s
   864   125 27913.8228   75  417 27882.7798 27924.9605  0.15%   409 1189s
   865   126 27913.8228  104  429 27882.7798 27921.6325  0.14%   408 1191s
   867   127 27913.8228  104  418 27882.7798 27921.1755  0.14%   407 1199s
   868   128 27913.8228   74  420 27882.7798 27916.5648  0.12%   407 1208s
   869   129 27913.8228   96  428 27882.7798 27916.5648  0.12%   407 1212s
   872   131 27913.8228   96  385 27882.7798 27915.2594  0.12%   405 1216s
   873   131 27906.1240  105  412 27882.7798 27906.1240  0.08%   405 1223s
   874   132 27906.1240   75  410 27882.7798 27906.1240  0.08%   404 1231s
   875   133 27903.4567    8  401 27882.7798 27903.4567  0.07%   404 1242s
   878   135 27899.8423   59  388 27882.7798 27899.8423  0.06%   402 1245s
   880   136 27899.3988   11  391 27882.7798 27899.3988  0.06%   401 1252s
   881   137 27896.5765    8  465 27882.7798 27896.5765  0.05%   401 1273s
   882   137 27896.5765    6  489 27882.7798 27896.5765  0.05%   401 1277s
   885   139 27896.5765   95  490 27882.7798 27896.5765  0.05%   399 1285s
   886   140 27896.5765  104  470 27882.7798 27896.5765  0.05%   399 1302s
   887   141 27896.2058   70  460 27882.7798 27896.2058  0.05%   398 1305s
   888   141 27896.1721   84  480 27882.7798 27896.1721  0.05%   398 1310s
   892   144 27892.6235   90  463 27882.7798 27892.6235  0.04%   396 1318s
   893   145 27887.7840   83  460 27882.7798 27887.7840  0.02%   396 1344s
   894   145 27887.7840   99  451 27882.7798 27887.7840  0.02%   395 1346s

Cutting planes:
  Gomory: 4
  Cover: 7
  Implied bound: 163
  Projected implied bound: 6
  MIR: 23
  Mixing: 2
  StrongCG: 5
  Flow cover: 52
  Inf proof: 1
  Zero half: 5
  RLT: 76
  Relax-and-lift: 111
  BQP: 12

Explored 898 nodes (581326 simplex iterations) in 1348.36 seconds (1215.00 work units)
Thread count was 8 (of 8 available processors)

Solution count 10: 27882.8 27663.5 27632.3 ... 25295.1

Optimal solution found (tolerance 1.00e-04)
Best objective 2.788277981563e+04, best bound 2.788535416922e+04, gap 0.0092%
Optimal combined objective value: 27882.779815633698
Selected objects:
Object x_1_1 selected
Object x_246_246 selected
Object x_250_250 selected
Object x_260_260 selected
Object x_262_262 selected
Object x_263_263 selected
Object x_265_265 selected
Object x_266_266 selected
Object x_269_269 selected
Object x_270_270 selected
Object x_272_272 selected
Object x_273_273 selected
Object x_274_274 selected
Object x_275_275 selected
Object x_276_276 selected
Object x_277_277 selected
Object x_278_278 selected
Object x_279_279 selected
Optimal routing:
Route: City 0 -> City 242
Route: City 1 -> City 245
Route: City 2 -> City 201
Route: City 3 -> City 71
Route: City 4 -> City 198
Route: City 5 -> City 116
Route: City 6 -> City 95
Route: City 7 -> City 236
Route: City 8 -> City 170
Route: City 9 -> City 190
Route: City 10 -> City 200
Route: City 11 -> City 156
Route: City 12 -> City 276
Route: City 13 -> City 149
Route: City 14 -> City 18
Route: City 15 -> City 158
Route: City 16 -> City 54
Route: City 17 -> City 277
Route: City 18 -> City 107
Route: City 19 -> City 204
Route: City 20 -> City 44
Route: City 21 -> City 168
Route: City 22 -> City 164
Route: City 23 -> City 8
Route: City 24 -> City 10
Route: City 25 -> City 133
Route: City 26 -> City 101
Route: City 27 -> City 148
Route: City 28 -> City 129
Route: City 29 -> City 195
Route: City 30 -> City 83
Route: City 31 -> City 28
Route: City 32 -> City 192
Route: City 33 -> City 92
Route: City 34 -> City 124
Route: City 35 -> City 52
Route: City 36 -> City 179
Route: City 37 -> City 120
Route: City 38 -> City 79
Route: City 39 -> City 219
Route: City 40 -> City 137
Route: City 41 -> City 228
Route: City 42 -> City 34
Route: City 43 -> City 66
Route: City 44 -> City 31
Route: City 45 -> City 63
Route: City 46 -> City 161
Route: City 47 -> City 188
Route: City 48 -> City 57
Route: City 49 -> City 205
Route: City 50 -> City 123
Route: City 51 -> City 61
Route: City 52 -> City 43
Route: City 53 -> City 141
Route: City 54 -> City 41
Route: City 55 -> City 232
Route: City 56 -> City 181
Route: City 57 -> City 138
Route: City 58 -> City 214
Route: City 59 -> City 246
Route: City 60 -> City 84
Route: City 61 -> City 202
Route: City 62 -> City 112
Route: City 63 -> City 23
Route: City 64 -> City 226
Route: City 65 -> City 231
Route: City 66 -> City 235
Route: City 67 -> City 189
Route: City 68 -> City 75
Route: City 69 -> City 21
Route: City 70 -> City 153
Route: City 71 -> City 147
Route: City 72 -> City 108
Route: City 73 -> City 40
Route: City 74 -> City 173
Route: City 75 -> City 217
Route: City 76 -> City 167
Route: City 77 -> City 5
Route: City 78 -> City 24
Route: City 79 -> City 35
Route: City 80 -> City 223
Route: City 81 -> City 212
Route: City 82 -> City 16
Route: City 83 -> City 175
Route: City 84 -> City 77
Route: City 85 -> City 233
Route: City 86 -> City 115
Route: City 87 -> City 99
Route: City 88 -> City 119
Route: City 89 -> City 159
Route: City 90 -> City 60
Route: City 91 -> City 4
Route: City 92 -> City 122
Route: City 93 -> City 74
Route: City 94 -> City 85
Route: City 95 -> City 221
Route: City 96 -> City 225
Route: City 97 -> City 14
Route: City 98 -> City 48
Route: City 99 -> City 180
Route: City 100 -> City 39
Route: City 101 -> City 241
Route: City 102 -> City 12
Route: City 103 -> City 73
Route: City 104 -> City 87
Route: City 105 -> City 118
Route: City 106 -> City 45
Route: City 107 -> City 163
Route: City 108 -> City 19
Route: City 109 -> City 154
Route: City 110 -> City 11
Route: City 111 -> City 20
Route: City 112 -> City 174
Route: City 113 -> City 127
Route: City 114 -> City 89
Route: City 115 -> City 177
Route: City 116 -> City 117
Route: City 117 -> City 152
Route: City 118 -> City 157
Route: City 119 -> City 162
Route: City 120 -> City 178
Route: City 121 -> City 27
Route: City 122 -> City 114
Route: City 123 -> City 55
Route: City 124 -> City 104
Route: City 125 -> City 6
Route: City 126 -> City 145
Route: City 127 -> City 131
Route: City 128 -> City 206
Route: City 129 -> City 80
Route: City 130 -> City 227
Route: City 131 -> City 267
Route: City 132 -> City 64
Route: City 133 -> City 183
Route: City 134 -> City 69
Route: City 135 -> City 128
Route: City 136 -> City 111
Route: City 137 -> City 222
Route: City 138 -> City 220
Route: City 139 -> City 155
Route: City 140 -> City 49
Route: City 141 -> City 143
Route: City 142 -> City 46
Route: City 143 -> City 76
Route: City 144 -> City 275
Route: City 145 -> City 70
Route: City 146 -> City 197
Route: City 147 -> City 88
Route: City 148 -> City 150
Route: City 149 -> City 98
Route: City 150 -> City 106
Route: City 151 -> City 186
Route: City 152 -> City 218
Route: City 153 -> City 176
Route: City 154 -> City 171
Route: City 155 -> City 172
Route: City 156 -> City 72
Route: City 157 -> City 65
Route: City 158 -> City 32
Route: City 159 -> City 105
Route: City 160 -> City 194
Route: City 161 -> City 166
Route: City 162 -> City 263
Route: City 163 -> City 187
Route: City 164 -> City 269
Route: City 165 -> City 56
Route: City 166 -> City 110
Route: City 167 -> City 165
Route: City 168 -> City 50
Route: City 169 -> City 182
Route: City 170 -> City 193
Route: City 171 -> City 203
Route: City 172 -> City 125
Route: City 173 -> City 78
Route: City 174 -> City 22
Route: City 175 -> City 37
Route: City 176 -> City 210
Route: City 177 -> City 67
Route: City 178 -> City 29
Route: City 179 -> City 213
Route: City 180 -> City 93
Route: City 181 -> City 184
Route: City 182 -> City 216
Route: City 183 -> City 42
Route: City 184 -> City 237
Route: City 185 -> City 126
Route: City 186 -> City 102
Route: City 187 -> City 59
Route: City 188 -> City 279
Route: City 189 -> City 0
Route: City 190 -> City 121
Route: City 191 -> City 86
Route: City 192 -> City 25
Route: City 193 -> City 90
Route: City 194 -> City 130
Route: City 195 -> City 224
Route: City 196 -> City 199
Route: City 197 -> City 247
Route: City 198 -> City 30
Route: City 199 -> City 58
Route: City 200 -> City 135
Route: City 201 -> City 97
Route: City 202 -> City 91
Route: City 203 -> City 38
Route: City 204 -> City 113