In [27]:
from utils import *
from heuristique_glouton import *
from heuristique_itérative import *
from evaluation import *

In [28]:
df_ville,df_object,capacity=parse_ttp_file("a280_n279_bounded-strongly-corr_01.ttp")

In [29]:
df_ville

       X    Y
1    288  149
2    288  129
3    270  133
4    256  141
5    256  157
..   ...  ...
276  236  145
277  246  141
278  252  125
279  260  129
280  280  133

[280 rows x 2 columns]

In [30]:
df_object

     Profit  Weight  City_Index
1       101       1           2
2       202       2           3
3       404       4           4
4       202       2           5
5       996     896           6
..      ...     ...         ...
275     786     686         276
276    1572    1372         277
277     786     686         278
278     566     466         279
279     456     356         280

[279 rows x 3 columns]

In [31]:
pi,obj_pris,poids_tot,dict_ville_objet_pris=algo_glouton(df_ville,df_object,capacity)

Loading:  96%|█████████▌| 24949/25936 [00:12<00:00, 1993.20weight unit/s, Current Weight=24949, Nb_ville=254]

In [32]:
for ville in pi:
    print("Dans la ville ",ville," le voleur prend ",len(dict_ville_objet_pris[ville])," objet(s).")

Dans la ville  1  le voleur prend  0  objet(s).
Dans la ville  6  le voleur prend  0  objet(s).
Dans la ville  7  le voleur prend  0  objet(s).
Dans la ville  178  le voleur prend  0  objet(s).
Dans la ville  99  le voleur prend  0  objet(s).
Dans la ville  96  le voleur prend  0  objet(s).
Dans la ville  97  le voleur prend  0  objet(s).
Dans la ville  98  le voleur prend  0  objet(s).
Dans la ville  93  le voleur prend  0  objet(s).
Dans la ville  94  le voleur prend  0  objet(s).
Dans la ville  95  le voleur prend  0  objet(s).
Dans la ville  76  le voleur prend  0  objet(s).
Dans la ville  117  le voleur prend  0  objet(s).
Dans la ville  115  le voleur prend  0  objet(s).
Dans la ville  116  le voleur prend  0  objet(s).
Dans la ville  64  le voleur prend  0  objet(s).
Dans la ville  56  le voleur prend  0  objet(s).
Dans la ville  55  le voleur prend  0  objet(s).
Dans la ville  54  le voleur prend  0  objet(s).
Dans la ville  53  le voleur prend  0  objet(s).
Dans la ville  38  le voleur prend  0  objet(s).
Dans la ville  39  le voleur prend  0  objet(s).
Dans la ville  40  le voleur prend  0  objet(s).
Dans la ville  41  le voleur prend  0  objet(s).
Dans la ville  42  le voleur prend  0  objet(s).
Dans la ville  43  le voleur prend  0  objet(s).
Dans la ville  60  le voleur prend  1  objet(s).
Dans la ville  61  le voleur prend  0  objet(s).
Dans la ville  118  le voleur prend  0  objet(s).
Dans la ville  62  le voleur prend  0  objet(s).
Dans la ville  63  le voleur prend  0  objet(s).
Dans la ville  59  le voleur prend  0  objet(s).
Dans la ville  58  le voleur prend  0  objet(s).
Dans la ville  57  le voleur prend  0  objet(s).
Dans la ville  44  le voleur prend  1  objet(s).
Dans la ville  45  le voleur prend  0  objet(s).
Dans la ville  46  le voleur prend  0  objet(s).
Dans la ville  47  le voleur prend  0  objet(s).
Dans la ville  48  le voleur prend  0  objet(s).
Dans la ville  49  le voleur prend  0  objet(s).
Dans la ville  52  le voleur prend  1  objet(s).
Dans la ville  51  le voleur prend  1  objet(s).
Dans la ville  50  le voleur prend  1  objet(s).
Dans la ville  37  le voleur prend  1  objet(s).
Dans la ville  36  le voleur prend  0  objet(s).
Dans la ville  35  le voleur prend  0  objet(s).
Dans la ville  34  le voleur prend  1  objet(s).
Dans la ville  33  le voleur prend  0  objet(s).
Dans la ville  32  le voleur prend  0  objet(s).
Dans la ville  30  le voleur prend  1  objet(s).
Dans la ville  31  le voleur prend  0  objet(s).
Dans la ville  29  le voleur prend  0  objet(s).
Dans la ville  28  le voleur prend  0  objet(s).
Dans la ville  27  le voleur prend  0  objet(s).
Dans la ville  26  le voleur prend  0  objet(s).
Dans la ville  22  le voleur prend  1  objet(s).
Dans la ville  25  le voleur prend  0  objet(s).
Dans la ville  23  le voleur prend  0  objet(s).
Dans la ville  24  le voleur prend  0  objet(s).
Dans la ville  14  le voleur prend  0  objet(s).
Dans la ville  15  le voleur prend  0  objet(s).
Dans la ville  13  le voleur prend  0  objet(s).
Dans la ville  12  le voleur prend  0  objet(s).
Dans la ville  11  le voleur prend  0  objet(s).
Dans la ville  10  le voleur prend  1  objet(s).
Dans la ville  8  le voleur prend  0  objet(s).
Dans la ville  9  le voleur prend  1  objet(s).
Dans la ville  259  le voleur prend  0  objet(s).
Dans la ville  260  le voleur prend  0  objet(s).
Dans la ville  261  le voleur prend  0  objet(s).
Dans la ville  262  le voleur prend  0  objet(s).
Dans la ville  270  le voleur prend  0  objet(s).
Dans la ville  269  le voleur prend  0  objet(s).
Dans la ville  135  le voleur prend  0  objet(s).
Dans la ville  134  le voleur prend  0  objet(s).
Dans la ville  133  le voleur prend  1  objet(s).
Dans la ville  18  le voleur prend  0  objet(s).
Dans la ville  17  le voleur prend  0  objet(s).
Dans la ville  16  le voleur prend  0  objet(s).
Dans la ville  271  le voleur prend  0  objet(s).
Dans la ville  272  le voleur prend  0  objet(s).
Dans la ville  273  le voleur prend  0  objet(s).
Dans la ville  274  le voleur prend  0  objet(s).
Dans la ville  275  le voleur prend  0  objet(s).
Dans la ville  276  le voleur prend  0  objet(s).
Dans la ville  277  le voleur prend  0  objet(s).
Dans la ville  242  le voleur prend  0  objet(s).
Dans la ville  243  le voleur prend  0  objet(s).
Dans la ville  280  le voleur prend  1  objet(s).
Dans la ville  279  le voleur prend  0  objet(s).
Dans la ville  278  le voleur prend  0  objet(s).
Dans la ville  248  le voleur prend  0  objet(s).
Dans la ville  247  le voleur prend  0  objet(s).
Dans la ville  238  le voleur prend  0  objet(s).
Dans la ville  239  le voleur prend  0  objet(s).
Dans la ville  240  le voleur prend  0  objet(s).
Dans la ville  241  le voleur prend  0  objet(s).
Dans la ville  244  le voleur prend  0  objet(s).
Dans la ville  245  le voleur prend  0  objet(s).
Dans la ville  246  le voleur prend  0  objet(s).
Dans la ville  231  le voleur prend  0  objet(s).
Dans la ville  233  le voleur prend  0  objet(s).
Dans la ville  232  le voleur prend  0  objet(s).
Dans la ville  237  le voleur prend  0  objet(s).
Dans la ville  236  le voleur prend  0  objet(s).
Dans la ville  235  le voleur prend  0  objet(s).
Dans la ville  234  le voleur prend  0  objet(s).
Dans la ville  218  le voleur prend  0  objet(s).
Dans la ville  219  le voleur prend  0  objet(s).
Dans la ville  223  le voleur prend  1  objet(s).
Dans la ville  224  le voleur prend  1  objet(s).
Dans la ville  225  le voleur prend  1  objet(s).
Dans la ville  226  le voleur prend  1  objet(s).
Dans la ville  227  le voleur prend  0  objet(s).
Dans la ville  228  le voleur prend  0  objet(s).
Dans la ville  229  le voleur prend  0  objet(s).
Dans la ville  230  le voleur prend  0  objet(s).
Dans la ville  251  le voleur prend  0  objet(s).
Dans la ville  250  le voleur prend  0  objet(s).
Dans la ville  249  le voleur prend  0  objet(s).
Dans la ville  252  le voleur prend  0  objet(s).
Dans la ville  253  le voleur prend  0  objet(s).
Dans la ville  254  le voleur prend  0  objet(s).
Dans la ville  255  le voleur prend  0  objet(s).
Dans la ville  256  le voleur prend  1  objet(s).
Dans la ville  257  le voleur prend  1  objet(s).
Dans la ville  258  le voleur prend  1  objet(s).
Dans la ville  263  le voleur prend  0  objet(s).
Dans la ville  264  le voleur prend  0  objet(s).
Dans la ville  265  le voleur prend  0  objet(s).
Dans la ville  149  le voleur prend  0  objet(s).
Dans la ville  150  le voleur prend  1  objet(s).
Dans la ville  179  le voleur prend  0  objet(s).
Dans la ville  180  le voleur prend  0  objet(s).
Dans la ville  186  le voleur prend  0  objet(s).
Dans la ville  184  le voleur prend  0  objet(s).
Dans la ville  174  le voleur prend  0  objet(s).
Dans la ville  173  le voleur prend  0  objet(s).
Dans la ville  106  le voleur prend  0  objet(s).
Dans la ville  105  le voleur prend  1  objet(s).
Dans la ville  104  le voleur prend  0  objet(s).
Dans la ville  103  le voleur prend  0  objet(s).
Dans la ville  169  le voleur prend  0  objet(s).
Dans la ville  170  le voleur prend  0  objet(s).
Dans la ville  171  le voleur prend  0  objet(s).
Dans la ville  172  le voleur prend  0  objet(s).
Dans la ville  166  le voleur prend  0  objet(s).
Dans la ville  167  le voleur prend  1  objet(s).
Dans la ville  168  le voleur prend  1  objet(s).
Dans la ville  100  le voleur prend  0  objet(s).
Dans la ville  101  le voleur prend  0  objet(s).
Dans la ville  102  le voleur prend  1  objet(s).
Dans la ville  92  le voleur prend  1  objet(s).
Dans la ville  91  le voleur prend  0  objet(s).
Dans la ville  90  le voleur prend  0  objet(s).
Dans la ville  112  le voleur prend  0  objet(s).
Dans la ville  110  le voleur prend  0  objet(s).
Dans la ville  111  le voleur prend  0  objet(s).
Dans la ville  114  le voleur prend  0  objet(s).
Dans la ville  113  le voleur prend  0  objet(s).
Dans la ville  84  le voleur prend  0  objet(s).
Dans la ville  83  le voleur prend  0  objet(s).
Dans la ville  82  le voleur prend  0  objet(s).
Dans la ville  81  le voleur prend  0  objet(s).
Dans la ville  80  le voleur prend  0  objet(s).
Dans la ville  79  le voleur prend  0  objet(s).
Dans la ville  78  le voleur prend  0  objet(s).
Dans la ville  77  le voleur prend  0  objet(s).
Dans la ville  75  le voleur prend  0  objet(s).
Dans la ville  74  le voleur prend  0  objet(s).
Dans la ville  73  le voleur prend  0  objet(s).
Dans la ville  72  le voleur prend  0  objet(s).
Dans la ville  71  le voleur prend  0  objet(s).
Dans la ville  70  le voleur prend  0  objet(s).
Dans la ville  69  le voleur prend  1  objet(s).
Dans la ville  68  le voleur prend  1  objet(s).
Dans la ville  67  le voleur prend  1  objet(s).
Dans la ville  66  le voleur prend  1  objet(s).
Dans la ville  65  le voleur prend  0  objet(s).
Dans la ville  85  le voleur prend  1  objet(s).
Dans la ville  86  le voleur prend  1  objet(s).
Dans la ville  87  le voleur prend  1  objet(s).
Dans la ville  88  le voleur prend  1  objet(s).
Dans la ville  89  le voleur prend  0  objet(s).
Dans la ville  109  le voleur prend  1  objet(s).
Dans la ville  108  le voleur prend  1  objet(s).
Dans la ville  107  le voleur prend  1  objet(s).
Dans la ville  165  le voleur prend  0  objet(s).
Dans la ville  164  le voleur prend  0  objet(s).
Dans la ville  163  le voleur prend  0  objet(s).
Dans la ville  162  le voleur prend  0  objet(s).
Dans la ville  161  le voleur prend  0  objet(s).
Dans la ville  175  le voleur prend  0  objet(s).
Dans la ville  160  le voleur prend  0  objet(s).
Dans la ville  159  le voleur prend  1  objet(s).
Dans la ville  158  le voleur prend  1  objet(s).
Dans la ville  157  le voleur prend  0  objet(s).
Dans la ville  119  le voleur prend  0  objet(s).
Dans la ville  120  le voleur prend  0  objet(s).
Dans la ville  121  le voleur prend  0  objet(s).
Dans la ville  122  le voleur prend  0  objet(s).
Dans la ville  123  le voleur prend  0  objet(s).
Dans la ville  124  le voleur prend  0  objet(s).
Dans la ville  125  le voleur prend  0  objet(s).
Dans la ville  126  le voleur prend  1  objet(s).
Dans la ville  127  le voleur prend  1  objet(s).
Dans la ville  130  le voleur prend  0  objet(s).
Dans la ville  131  le voleur prend  0  objet(s).
Dans la ville  132  le voleur prend  0  objet(s).
Dans la ville  19  le voleur prend  1  objet(s).
Dans la ville  20  le voleur prend  1  objet(s).
Dans la ville  21  le voleur prend  1  objet(s).
Dans la ville  128  le voleur prend  1  objet(s).
Dans la ville  129  le voleur prend  1  objet(s).
Dans la ville  154  le voleur prend  0  objet(s).
Dans la ville  155  le voleur prend  0  objet(s).
Dans la ville  153  le voleur prend  1  objet(s).
Dans la ville  156  le voleur prend  0  objet(s).
Dans la ville  152  le voleur prend  1  objet(s).
Dans la ville  151  le voleur prend  1  objet(s).
Dans la ville  177  le voleur prend  0  objet(s).
Dans la ville  176  le voleur prend  0  objet(s).
Dans la ville  181  le voleur prend  0  objet(s).
Dans la ville  182  le voleur prend  1  objet(s).
Dans la ville  183  le voleur prend  1  objet(s).
Dans la ville  185  le voleur prend  0  objet(s).
Dans la ville  187  le voleur prend  1  objet(s).
Dans la ville  188  le voleur prend  0  objet(s).
Dans la ville  189  le voleur prend  0  objet(s).
Dans la ville  190  le voleur prend  0  objet(s).
Dans la ville  191  le voleur prend  0  objet(s).
Dans la ville  192  le voleur prend  0  objet(s).
Dans la ville  193  le voleur prend  0  objet(s).
Dans la ville  196  le voleur prend  0  objet(s).
Dans la ville  195  le voleur prend  0  objet(s).
Dans la ville  194  le voleur prend  0  objet(s).
Dans la ville  197  le voleur prend  0  objet(s).
Dans la ville  198  le voleur prend  0  objet(s).
Dans la ville  199  le voleur prend  0  objet(s).
Dans la ville  145  le voleur prend  1  objet(s).
Dans la ville  146  le voleur prend  0  objet(s).
Dans la ville  147  le voleur prend  0  objet(s).
Dans la ville  148  le voleur prend  0  objet(s).
Dans la ville  139  le voleur prend  0  objet(s).
Dans la ville  138  le voleur prend  0  objet(s).
Dans la ville  137  le voleur prend  0  objet(s).
Dans la ville  136  le voleur prend  0  objet(s).
Dans la ville  268  le voleur prend  0  objet(s).
Dans la ville  267  le voleur prend  0  objet(s).
Dans la ville  266  le voleur prend  0  objet(s).
Dans la ville  140  le voleur prend  0  objet(s).
Dans la ville  141  le voleur prend  0  objet(s).
Dans la ville  142  le voleur prend  1  objet(s).
Dans la ville  143  le voleur prend  1  objet(s).
Dans la ville  144  le voleur prend  1  objet(s).
Dans la ville  200  le voleur prend  0  objet(s).
Dans la ville  201  le voleur prend  0  objet(s).
Dans la ville  202  le voleur prend  0  objet(s).
Dans la ville  203  le voleur prend  0  objet(s).
Dans la ville  204  le voleur prend  0  objet(s).
Dans la ville  205  le voleur prend  0  objet(s).
Dans la ville  206  le voleur prend  0  objet(s).
Dans la ville  207  le voleur prend  0  objet(s).
Dans la ville  208  le voleur prend  1  objet(s).
Dans la ville  209  le voleur prend  1  objet(s).
Dans la ville  210  le voleur prend  1  objet(s).
Dans la ville  211  le voleur prend  1  objet(s).
Dans la ville  212  le voleur prend  1  objet(s).
Dans la ville  213  le voleur prend  1  objet(s).
Dans la ville  214  le voleur prend  1  objet(s).
Dans la ville  215  le voleur prend  1  objet(s).
Dans la ville  216  le voleur prend  1  objet(s).
Dans la ville  217  le voleur prend  1  objet(s).
Dans la ville  220  le voleur prend  1  objet(s).
Dans la ville  221  le voleur prend  1  objet(s).
Dans la ville  222  le voleur prend  1  objet(s).
Dans la ville  5  le voleur prend  1  objet(s).
Dans la ville  4  le voleur prend  1  objet(s).
Dans la ville  3  le voleur prend  1  objet(s).
Dans la ville  2  le voleur prend  1  objet(s).

In [33]:
eval_non_lin(pi,df_ville,df_object,dict_ville_objet_pris,obj_pris,capacity)

yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
BENEFICE :  39249
COUT :  6840.9321285460655

(32408.067871453935, 39249, 6840.9321285460655)

In [34]:
eval_lin(pi,df_ville,df_object,dict_ville_objet_pris,obj_pris)

yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
yes
BENEFICE :  39249
COUT :  31281285.950658288

(-31242036.950658288, 39249, 31281285.950658288)

In [35]:
import gurobipy as gp

# Initialize combined model
model = gp.Model("CombinedModel")

# Decision variables for object selection
dict_obj_ville = {}
list_index_ville = list(df_ville.index)
list_obj = []

for index_ville in list_index_ville:
    list_index_obj = list(get_objects_of_ville(index_ville + 1, df_object).index)
    dict_obj_ville[index_ville] = []
    for index_obj in list_index_obj:
        x = model.addVar(vtype=gp.GRB.BINARY, name=f"x_{index_ville}_{index_obj}")
        dict_obj_ville[index_ville].append(x)
        list_obj.append(x)


# Decision variables for routing
n = len(list_index_ville)
y = [
    [model.addVar(vtype=gp.GRB.BINARY, name=f"y_{i}_{j}") for j in range(n)]
    for i in range(n)
]

# Auxiliary variables for cumulative weight
w = model.addVars(n, vtype=gp.GRB.CONTINUOUS, lb=0, name="w")

w_transfers=model.addVars(n, vtype=gp.GRB.CONTINUOUS, lb=0, name="w_transfer")

model.addConstr(w_transfers[0]==0)

# Auxiliary variables for MTZ constraints
u = model.addVars(n, vtype=gp.GRB.CONTINUOUS, lb=1, ub=n, name="u")

# Define weights and profits for object selection
list_poids = [df_object.iloc[i]["Weight"] for i in range(len(list_obj))]
list_benefits = [df_object.iloc[i]["Profit"] for i in range(len(list_obj))]

# Define distance matrix
matrix_distance = {i: calcul_distance_de_ville(i, df_ville) for i in list_index_ville}

# Add capacity constraint
model.addConstr(
    gp.quicksum(list_poids[i] * list_obj[i] for i in range(len(list_poids))) <= capacity,
    "Capacity"
)

# Add routing constraints
model.addConstrs(
    (gp.quicksum(y[i][j] for j in range(n) if j != i) == 1 for i in range(n)), "Depart"
)
model.addConstrs(
    (gp.quicksum(y[i][j] for i in range(n) if i != j) == 1 for j in range(n)), "Arrive"
)

# Ensure objects are selected only if their cities are visited
for index_ville, vars_list in dict_obj_ville.items():
    for obj_var in vars_list:
        model.addConstr(
            gp.quicksum(y[index_ville][j] for j in range(n) if j != index_ville) >= obj_var,
            f"ObjectSelectedIfCityVisited_{index_ville}"
        )

# Add cumulative weight constraints
for i in range(n):
    model.addConstr(
        w[i] == gp.quicksum(dict_obj_ville[i+1][k] * list_poids[k] for k in range(len(dict_obj_ville[i+1]))),
        f"CumulativeWeight_{i}"
    )
    if i > 0:
        model.addConstr(w_transfers[i] == w[i] + w_transfers[i-1],f"WeightTransfer_{i}")

# Add MTZ constraints to eliminate subtours
for i in range(1, n):  # Start from 1 since city 0 is the starting point
    for j in range(1, n):  # MTZ does not apply for starting city
        if i != j:
            model.addConstr(
                u[i] - u[j] + n * y[i][j] <= n - 1,
                name=f"SubtourElimination_{i}_{j}"
            )

# Define objective function
profit = gp.quicksum(list_benefits[i] * list_obj[i] for i in range(len(list_benefits)))
routing_cost = gp.quicksum(
    matrix_distance[i + 1][j + 1] * y[i][j] * w[i] for i in range(n) for j in range(n)
)

# Combine objectives: maximize profit and minimize routing cost
alpha = 1  # Weight for profit
beta = 1   # Weight for routing cost (adjust based on importance)
model.setObjective(alpha * profit-beta*routing_cost, gp.GRB.MAXIMIZE)

# Optimize the model
model.optimize()

# Print results
if model.status == gp.GRB.OPTIMAL:
    print(f"Optimal combined objective value: {model.objVal}")
    print("Selected objects:")
    for index_ville, vars_list in dict_obj_ville.items():
        for obj_var in vars_list:
            if obj_var.x > 0.5:
                print(f"Object {obj_var.varName} selected")
    print("Optimal routing:")
    for i in range(n):
        for j in range(n):
            if y[i][j].x > 0.5:
                print(f"Route: City {i} -> City {j}")

Gurobi Optimizer version 12.0.0 build v12.0.0rc1 (win64 - Windows 10.0 (19045.2))

CPU model: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 78962 rows, 79519 columns and 468722 nonzeros
Model fingerprint: 0xdccd3911
Model has 78118 quadratic objective terms
Variable types: 840 continuous, 78679 integer (78679 binary)
Coefficient statistics:
  Matrix range     [1e+00, 4e+03]
  Objective range  [1e+02, 4e+03]
  QObjective range [2e+01, 6e+02]
  Bounds range     [1e+00, 3e+02]
  RHS range        [1e+00, 3e+04]
Presolve removed 839 rows and 841 columns
Presolve time: 1.00s
Presolved: 155962 rows, 156517 columns, 622722 nonzeros
Variable types: 279 continuous, 156238 integer (156238 binary)
Deterministic concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Root barrier log...

Ordering time: 0.08s

Barrier statistics:
 Dense cols : 558
 AA' NZ     : 6.994e+05
 Factor NZ  : 1.633e+06 (roughly 140 MB of memory)
 Factor Ops : 4.714e+08 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -1.98937990e+09  3.57592986e+07  5.87e+04 5.68e-14  7.25e+04     6s
   1  -1.43057200e+09  7.48753806e+07  4.14e+04 4.16e+02  5.22e+04     6s
   2  -1.19645680e+09  3.62830615e+08  3.29e+04 9.40e+01  4.10e+04     7s
   3  -8.45970969e+08  3.70823268e+08  2.29e+04 1.24e+02  2.88e+04     7s
   4  -5.01179901e+07  4.06330406e+08  1.08e+03 3.72e-10  2.23e+03     8s
   5  -3.75866622e+06  5.66212211e+07  1.44e-11 2.15e-10  1.29e+02     8s
   6  -2.07010101e+06  2.05217408e+07  3.38e-13 9.30e-11  4.82e+01     8s
   7  -1.12292620e+06  8.22300668e+06  1.80e-14 3.93e-11  2.00e+01     9s
   8  -3.55376854e+05  3.74539506e+06  1.40e-14 2.36e-11  8.75e+00     9s
   9  -8.13673954e+04  2.94654668e+06  7.66e-15 1.91e-11  6.46e+00     9s
  10  -7.51480314e+04  1.88077405e+06  7.88e-15 1.42e-11  4.18e+00    10s
  11   1.67315833e+04  4.27404971e+05  4.66e-15 2.44e-12  8.77e-01    10s
  12   3.01252182e+04  1.71602005e+05  5.11e-15 3.06e-12  3.02e-01    10s
  13   3.48604753e+04  1.16674554e+05  1.40e-14 2.62e-11  1.75e-01    10s
  14   3.63114825e+04  7.44036048e+04  1.02e-14 3.73e-11  8.13e-02    11s
  15   3.73738674e+04  6.07127969e+04  1.24e-14 7.96e-11  4.98e-02    11s
  16   4.05338705e+04  4.56556232e+04  3.33e-15 1.78e-10  1.09e-02    11s
  17   4.10203372e+04  4.29023136e+04  8.33e-15 2.26e-10  4.02e-03    12s
  18   4.11138301e+04  4.27286979e+04  1.17e-14 2.18e-10  3.45e-03    12s
  19   4.14115230e+04  4.24146359e+04  4.00e-15 3.11e-10  2.14e-03    12s
  20   4.14425491e+04  4.22530708e+04  2.78e-15 4.01e-10  1.73e-03    12s
  21   4.18587493e+04  4.21353826e+04  9.99e-15 6.76e-10  5.91e-04    12s
  22   4.19489553e+04  4.21109695e+04  1.83e-14 6.67e-10  3.46e-04    13s
  23   4.20081094e+04  4.21035637e+04  1.31e-14 6.42e-10  2.04e-04    13s
  24   4.20549430e+04  4.20999081e+04  2.46e-13 3.64e-10  9.60e-05    13s
  25   4.20964238e+04  4.20988322e+04  3.09e-14 1.41e-09  5.14e-06    13s
  26   4.20979044e+04  4.20979753e+04  1.69e-14 3.21e-09  1.51e-07    14s
  27   4.20979601e+04  4.20979602e+04  8.66e-15 5.57e-12  1.51e-10    14s

Barrier solved model in 27 iterations and 13.73 seconds (6.73 work units)
Optimal objective 4.20979601e+04


Root crossover log...

   21764 DPushes remaining with DInf 0.0000000e+00                14s
       0 DPushes remaining with DInf 0.0000000e+00                15s

   56436 PPushes remaining with PInf 0.0000000e+00                15s
   51945 PPushes remaining with PInf 0.0000000e+00                15s
Concurrent spin time: 4.28s (can be avoided by choosing Method=3)

Solved with dual simplex

Root simplex log...

Iteration    Objective       Primal Inf.    Dual Inf.      Time
   23904    4.2097960e+04   0.000000e+00   0.000000e+00     15s

Root relaxation: objective 4.209796e+04, 23904 iterations, 10.67 seconds (5.22 work units)
Total elapsed time = 15.28s (DegenMoves)
Total elapsed time = 22.62s (DegenMoves)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 42097.9602    0 21837          - 42097.9602      -     -   24s
H    0     0                      -0.0000000 42097.9602      -     -   26s
H    0     0                    30320.429985 42097.9602  38.8%     -   26s
H    0     0                    30795.791568 41458.8588  34.6%     -   61s
H    0     0                    31140.832401 41458.8588  33.1%     -   61s
     0     0 41458.8588    0 5562 31140.8324 41458.8588  33.1%     -   63s
H    0     0                    36820.084072 41458.7434  12.6%     -   69s
H    0     0                    38782.084072 41458.7434  6.90%     -   69s
H    0     0                    40213.326439 41458.7434  3.10%     -   69s
H    0     0                    40587.291997 41458.7434  2.15%     -   75s
H    0     0                    40864.070637 41458.7434  1.46%     -   86s
H    0     0                    41049.871134 41458.7434  1.00%     -   93s
H    0     0                    41060.471255 41413.8943  0.86%     -  513s
H    0     0                    41072.636780 41413.8943  0.83%     -  513s
H    0     0                    41073.149741 41413.8943  0.83%     -  513s
H    0     0                    41089.202812 41413.8943  0.79%     -  513s
H    0     0                    41105.033372 41413.8943  0.75%     -  513s
H    0     0                    41194.681962 41413.8943  0.53%     -  513s
H    0     0                    41197.764210 41413.8943  0.52%     -  513s
H    0     0                    41230.896247 41413.8943  0.44%     -  513s
     0     0 41413.8943    0 5017 41230.8962 41413.8943  0.44%     -  515s
     0     0 41413.7366    0 2756 41230.8962 41413.7366  0.44%     -  522s
     0     0 41413.2968    0 3895 41230.8962 41413.2968  0.44%     -  535s
     0     0 41413.2968    0 18182 41230.8962 41413.2968  0.44%     -  564s
H    0     0                    41256.251382 41413.2968  0.38%     - 1655s
H    0     0                    41374.042573 41413.2968  0.09%     - 1655s
     0     0 41410.5621    0 3084 41374.0426 41410.5621  0.09%     - 1657s
     0     0 41408.8732    0 2812 41374.0426 41408.8732  0.08%     - 1665s
     0     0 41408.8732    0 2734 41374.0426 41408.8732  0.08%     - 1671s
     0     0 41408.8732    0 2242 41374.0426 41408.8732  0.08%     - 1689s
     0     0 41408.8732    0 2956 41374.0426 41408.8732  0.08%     - 1699s
H    0     0                    41384.042573 41408.8732  0.06%     - 1719s
     0     0 41408.8732    0  745 41384.0426 41408.8732  0.06%     - 1719s
H    0     0                    41392.042573 41408.8732  0.04%     - 1722s
     0     0 41408.8732    0  791 41392.0426 41408.8732  0.04%     - 1754s
     0     0 41405.2302    0  712 41392.0426 41405.2302  0.03%     - 1757s
     0     0 41405.2302    0  699 41392.0426 41405.2302  0.03%     - 1759s
     0     0 41400.7463    0  552 41392.0426 41400.7463  0.02%     - 1796s
     0     0 41400.7433    0  577 41392.0426 41400.7433  0.02%     - 1802s
     0     0 41400.6624    0  546 41392.0426 41400.6624  0.02%     - 1821s
     0     0 41400.4054    0  545 41392.0426 41400.4054  0.02%     - 1869s
     0     0 41400.3408    0  529 41392.0426 41400.3408  0.02%     - 1881s
     0     0 41400.0466    0  514 41392.0426 41400.0466  0.02%     - 1912s
     0     0 41399.7092    0  516 41392.0426 41399.7092  0.02%     - 1925s
     0     0 41399.7092    0  481 41392.0426 41399.7092  0.02%     - 1928s
     0     0 41399.7092    0  477 41392.0426 41399.7092  0.02%     - 1929s
     0     0 41399.7092    0  475 41392.0426 41399.7092  0.02%     - 1929s
     0     0 41399.5933    0  452 41392.0426 41399.5933  0.02%     - 1930s
     0     0 41399.5933    0  486 41392.0426 41399.5933  0.02%     - 1945s
     0     0 41399.5072    0  481 41392.0426 41399.5072  0.02%     - 1945s
     0     0 41399.2595    0  492 41392.0426 41399.2595  0.02%     - 1971s
     0     0 41399.0080    0  451 41392.0426 41399.0080  0.02%     - 1999s
     0     0 41398.6642    0  481 41392.0426 41398.6642  0.02%     - 2022s
     0     0 41398.5892    0  474 41392.0426 41398.5892  0.02%     - 2029s
     0     0 41398.4120    0  476 41392.0426 41398.4120  0.02%     - 2043s
     0     0 41398.3891    0  456 41392.0426 41398.3891  0.02%     - 2063s
     0     0 41398.2575    0  446 41392.0426 41398.2575  0.02%     - 2073s
     0     0          -    0      41392.0426 41394.5534  0.01%     - 2097s

Cutting planes:
  Learned: 2
  Gomory: 72
  Implied bound: 54
  Dual implied bound: 2
  Clique: 2
  MIR: 201
  StrongCG: 5
  Zero half: 53
  RLT: 217
  Relax-and-lift: 310
  BQP: 122

Explored 1 nodes (275530 simplex iterations) in 2097.48 seconds (894.87 work units)
Thread count was 8 (of 8 available processors)

Solution count 10: 41392 41384 41374 ... 41073.1

Optimal solution found (tolerance 1.00e-04)
Best objective 4.139204257306e+04, best bound 4.139455340870e+04, gap 0.0061%
Optimal combined objective value: 41392.04257306181
Selected objects:
Object x_1_1 selected
Object x_2_2 selected
Object x_3_3 selected
Object x_4_4 selected
Object x_18_18 selected
Object x_19_19 selected
Object x_20_20 selected
Object x_21_21 selected
Object x_35_35 selected
Object x_43_43 selected
Object x_46_46 selected
Object x_47_47 selected
Object x_49_49 selected
Object x_50_50 selected
Object x_51_51 selected
Object x_56_56 selected
Object x_57_57 selected
Object x_58_58 selected
Object x_59_59 selected
Object x_60_60 selected
Object x_61_61 selected
Object x_62_62 selected
Object x_63_63 selected
Object x_64_64 selected
Object x_65_65 selected
Object x_66_66 selected
Object x_67_67 selected
Object x_68_68 selected
Object x_84_84 selected
Object x_85_85 selected
Object x_86_86 selected
Object x_87_87 selected
Object x_88_88 selected
Object x_90_90 selected
Object x_91_91 selected
Object x_100_100 selected
Object x_101_101 selected
Object x_102_102 selected
Object x_103_103 selected
Object x_104_104 selected
Object x_106_106 selected
Object x_107_107 selected
Object x_108_108 selected
Object x_125_125 selected
Object x_126_126 selected
Object x_127_127 selected
Object x_128_128 selected
Object x_130_130 selected
Object x_149_149 selected
Object x_150_150 selected
Object x_151_151 selected
Object x_152_152 selected
Object x_157_157 selected
Object x_158_158 selected
Object x_159_159 selected
Object x_161_161 selected
Object x_166_166 selected
Object x_167_167 selected
Object x_181_181 selected
Object x_182_182 selected
Object x_210_210 selected
Object x_211_211 selected
Object x_212_212 selected
Object x_213_213 selected
Object x_214_214 selected
Object x_215_215 selected
Object x_216_216 selected
Object x_220_220 selected
Object x_221_221 selected
Object x_222_222 selected
Object x_223_223 selected
Object x_224_224 selected
Object x_225_225 selected
Object x_255_255 selected
Object x_256_256 selected
Object x_257_257 selected
Optimal routing:
Route: City 0 -> City 1
Route: City 1 -> City 279
Route: City 2 -> City 278
Route: City 3 -> City 276
Route: City 4 -> City 221
Route: City 5 -> City 53
Route: City 6 -> City 243
Route: City 7 -> City 261
Route: City 8 -> City 129
Route: City 9 -> City 252
Route: City 10 -> City 88
Route: City 11 -> City 39
Route: City 12 -> City 122
Route: City 13 -> City 10
Route: City 14 -> City 143
Route: City 15 -> City 34
Route: City 16 -> City 201
Route: City 17 -> City 132
Route: City 18 -> City 131
Route: City 19 -> City 18
Route: City 20 -> City 19
Route: City 21 -> City 33
Route: City 22 -> City 272
Route: City 23 -> City 179
Route: City 24 -> City 258
Route: City 25 -> City 72
Route: City 26 -> City 191
Route: City 27 -> City 193
Route: City 28 -> City 244
Route: City 29 -> City 178
Route: City 30 -> City 60
Route: City 31 -> City 119
Route: City 32 -> City 238
Route: City 33 -> City 77
Route: City 34 -> City 35
Route: City 35 -> City 149
Route: City 36 -> City 162
Route: City 37 -> City 241
Route: City 38 -> City 205
Route: City 39 -> City 38
Route: City 40 -> City 183
Route: City 41 -> City 116
Route: City 42 -> City 41
Route: City 43 -> City 170
Route: City 44 -> City 43
Route: City 45 -> City 54
Route: City 46 -> City 45
Route: City 47 -> City 52
Route: City 48 -> City 51
Route: City 49 -> City 48
Route: City 50 -> City 49
Route: City 51 -> City 135
Route: City 52 -> City 207
Route: City 53 -> City 30
Route: City 54 -> City 215
Route: City 55 -> City 44
Route: City 56 -> City 55
Route: City 57 -> City 56
Route: City 58 -> City 57
Route: City 59 -> City 42
Route: City 60 -> City 59
Route: City 61 -> City 117
Route: City 62 -> City 61
Route: City 63 -> City 62
Route: City 64 -> City 63
Route: City 65 -> City 64
Route: City 66 -> City 69
Route: City 67 -> City 68
Route: City 68 -> City 113
Route: City 69 -> City 95
Route: City 70 -> City 255
Route: City 71 -> City 89
Route: City 72 -> City 8
Route: City 73 -> City 76
Route: City 74 -> City 264
Route: City 75 -> City 120
Route: City 76 -> City 92
Route: City 77 -> City 5
Route: City 78 -> City 275
Route: City 79 -> City 146
Route: City 80 -> City 190
Route: City 81 -> City 249
Route: City 82 -> City 75
Route: City 83 -> City 86
Route: City 84 -> City 83
Route: City 85 -> City 115
Route: City 86 -> City 112
Route: City 87 -> City 111
Route: City 88 -> City 108
Route: City 89 -> City 90
Route: City 90 -> City 91
Route: City 91 -> City 142
Route: City 92 -> City 66
Route: City 93 -> City 242
Route: City 94 -> City 20
Route: City 95 -> City 153
Route: City 96 -> City 14
Route: City 97 -> City 28
Route: City 98 -> City 99
Route: City 99 -> City 100
Route: City 100 -> City 101
Route: City 101 -> City 102
Route: City 102 -> City 103
Route: City 103 -> City 104
Route: City 104 -> City 194
Route: City 105 -> City 172
Route: City 106 -> City 105
Route: City 107 -> City 109
Route: City 108 -> City 0
Route: City 109 -> City 273
Route: City 110 -> City 160
Route: City 111 -> City 245
Route: City 112 -> City 269
Route: City 113 -> City 4
Route: City 114 -> City 169
Route: City 115 -> City 192
Route: City 116 -> City 165
Route: City 117 -> City 58
Route: City 118 -> City 247
Route: City 119 -> City 80
Route: City 120 -> City 140
Route: City 121 -> City 152
Route: City 122 -> City 98
Route: City 123 -> City 168
Route: City 124 -> City 123
Route: City 125 -> City 126
Route: City 126 -> City 127
Route: City 127 -> City 128
Route: City 128 -> City 150
Route: City 129 -> City 130
Route: City 130 -> City 67
Route: City 131 -> City 27
Route: City 132 -> City 82
Route: City 133 -> City 270
Route: City 134 -> City 106
Route: City 135 -> City 199
Route: City 136 -> City 133
Route: City 137 -> City 26
Route: City 138 -> City 24
Route: City 139 -> City 37
Route: City 140 -> City 173
Route: City 141 -> City 93
Route: City 142 -> City 137
Route: City 143 -> City 195
Route: City 144 -> City 197
Route: City 145 -> City 274
Route: City 146 -> City 110
Route: City 147 -> City 71
Route: City 148 -> City 138
Route: City 149 -> City 148
Route: City 150 -> City 176
Route: City 151 -> City 155
Route: City 152 -> City 144
Route: City 153 -> City 6
Route: City 154 -> City 141
Route: City 155 -> City 240
Route: City 156 -> City 118
Route: City 157 -> City 156
Route: City 158 -> City 157
Route: City 159 -> City 174
Route: City 160 -> City 161
Route: City 161 -> City 235
Route: City 162 -> City 12
Route: City 163 -> City 251
Route: City 164 -> City 124
Route: City 165 -> City 166
Route: City 166 -> City 167
Route: City 167 -> City 159
Route: City 168 -> City 233
Route: City 169 -> City 13
Route: City 170 -> City 171
Route: City 171 -> City 74
Route: City 172 -> City 107
Route: City 173 -> City 96
Route: City 174 -> City 265
Route: City 175 -> City 267
Route: City 176 -> City 250
Route: City 177 -> City 222
Route: City 178 -> City 121
Route: City 179 -> City 73
Route: City 180 -> City 181
Route: City 181 -> City 182
Route: City 182 -> City 7
Route: City 183 -> City 184
Route: City 184 -> City 175
Route: City 185 -> City 189
Route: City 186 -> City 40
Route: City 187 -> City 139
Route: City 188 -> City 21
Route: City 189 -> City 47
Route: City 190 -> City 11
Route: City 191 -> City 196
Route: City 192 -> City 31
Route: City 193 -> City 188
Route: City 194 -> City 213
Route: City 195 -> City 78
Route: City 196 -> City 208
Route: City 197 -> City 271
Route: City 198 -> City 16
Route: City 199 -> City 202
Route: City 200 -> City 136
Route: City 201 -> City 151
Route: City 202 -> City 180
Route: City 203 -> City 125
Route: City 204 -> City 85
Route: City 205 -> City 22
Route: City 206 -> City 268
Route: City 207 -> City 81
Route: City 208 -> City 25
Route: City 209 -> City 206
Route: City 210 -> City 209
Route: City 211 -> City 210
Route: City 212 -> City 211
Route: City 213 -> City 212
Route: City 214 -> City 217
Route: City 215 -> City 214
Route: City 216 -> City 237
Route: City 217 -> City 200
Route: City 218 -> City 266
Route: City 219 -> City 216
Route: City 220 -> City 219
Route: City 221 -> City 218
Route: City 222 -> City 223
Route: City 223 -> City 224
Route: City 224 -> City 225
Route: City 225 -> City 231
Route: City 226 -> City 228
Route: City 227 -> City 50
Route: City 228 -> City 134
Route: City 229 -> City 114
Route: City 230 -> City 198
Route: City 231 -> City 65
Route: City 232 -> City 204
Route: City 233 -> City 163
Route: City 234 -> City 94
Route: City 235 -> City 29
Route: City 236 -> City 158
Route: City 237 -> City 277
Route: City 238 -> City 177
Route: City 239 -> City 23
Route: City 240 -> City 145
Route: City 241 -> City 248
Route: City 242 -> City 164
Route: City 243 -> City 236
Route: City 244 -> City 9
Route: City 245 -> City 3
Route: City 246 -> City 203
Route: City 247 -> City 2
Route: City 248 -> City 246
Route: City 249 -> City 229
Route: City 250 -> City 79
Route: City 251 -> City 147
Route: City 252 -> City 186
Route: City 253 -> City 84
Route: City 254 -> City 253
Route: City 255 -> City 254
Route: City 256 -> City 257
Route: City 257 -> City 15
Route: City 258 -> City 87
Route: City 259 -> City 226
Route: City 260 -> City 187
Route: City 261 -> City 263
Route: City 262 -> City 239
Route: City 263 -> City 230
Route: City 264 -> City 232
Route: City 265 -> City 256
Route: City 266 -> City 17
Route: City 267 -> City 70
Route: City 268 -> City 154
Route: City 269 -> City 36
Route: City 270 -> City 185
Route: City 271 -> City 262
Route: City 272 -> City 46
Route: City 273 -> City 97
Route: City 274 -> City 32
Route: City 275 -> City 220
Route: City 276 -> City 260
Route: City 277 -> City 234
Route: City 278 -> City 227
Route: City 279 -> City 259

In [36]:
print("Capacity:", capacity)
print("Weights:", list_poids)
print("Profits:", list_benefits)
print("Distance matrix:", matrix_distance)

Capacity: 25936
Weights: [1, 2, 4, 2, 896, 1792, 3584, 367, 734, 1468, 690, 690, 613, 1226, 2452, 874, 874, 122, 244, 488, 366, 486, 972, 972, 823, 823, 463, 926, 463, 589, 1178, 1178, 325, 650, 1300, 975, 1000, 2000, 4000, 776, 1552, 2328, 123, 356, 305, 610, 1220, 305, 47, 94, 188, 645, 1290, 2580, 1290, 139, 247, 494, 988, 741, 211, 422, 844, 633, 100, 200, 400, 100, 627, 1254, 1254, 760, 1520, 776, 1552, 3104, 475, 950, 1900, 937, 1874, 3748, 937, 101, 202, 404, 202, 281, 562, 1124, 562, 751, 1502, 3004, 1502, 530, 1060, 2120, 240, 480, 480, 248, 496, 744, 768, 31, 62, 31, 613, 1226, 2452, 613, 881, 1762, 1762, 367, 734, 1468, 367, 712, 410, 820, 1640, 410, 157, 314, 628, 471, 824, 242, 472, 944, 1416, 722, 1444, 2888, 775, 775, 371, 742, 1484, 337, 674, 337, 885, 1770, 3540, 1770, 204, 408, 816, 408, 594, 1188, 2376, 1188, 226, 452, 904, 226, 452, 921, 537, 1074, 2148, 112, 112, 959, 1918, 2877, 392, 392, 709, 1418, 2836, 940, 1880, 943, 1886, 3772, 79, 79, 922, 1844, 1844, 361, 947, 1894, 947, 861, 1722, 3444, 2583, 937, 1874, 3748, 2811, 754, 1508, 2262, 872, 636, 636, 459, 918, 1836, 1377, 390, 390, 141, 282, 423, 111, 222, 444, 333, 588, 1176, 588, 6, 6, 155, 310, 620, 465, 723, 1446, 2892, 1446, 723, 1446, 2892, 2169, 667, 1334, 1334, 829, 1658, 3316, 829, 487, 974, 974, 590, 1180, 2360, 1180, 370, 740, 1480, 823, 1646, 3292, 823, 173, 346, 56, 977, 1954, 2931, 681, 1362, 2043, 689, 1378, 2756, 689, 933, 1866, 2799, 809, 1618, 587, 1174, 686, 1372, 686, 466, 356]
Profits: [101, 202, 404, 202, 996, 1992, 3984, 467, 934, 1868, 790, 790, 713, 1426, 2852, 974, 974, 222, 444, 888, 666, 586, 1172, 1172, 923, 923, 563, 1126, 563, 689, 1378, 1378, 425, 850, 1700, 1275, 1100, 2200, 4400, 876, 1752, 2628, 223, 456, 405, 810, 1620, 405, 147, 294, 588, 745, 1490, 2980, 1490, 239, 347, 694, 1388, 1041, 311, 622, 1244, 933, 200, 400, 800, 200, 727, 1454, 1454, 860, 1720, 876, 1752, 3504, 575, 1150, 2300, 1037, 2074, 4148, 1037, 201, 402, 804, 402, 381, 762, 1524, 762, 851, 1702, 3404, 1702, 630, 1260, 2520, 340, 680, 680, 348, 696, 1044, 868, 131, 262, 131, 713, 1426, 2852, 713, 981, 1962, 1962, 467, 934, 1868, 467, 812, 510, 1020, 2040, 510, 257, 514, 1028, 771, 924, 342, 572, 1144, 1716, 822, 1644, 3288, 875, 875, 471, 942, 1884, 437, 874, 437, 985, 1970, 3940, 1970, 304, 608, 1216, 608, 694, 1388, 2776, 1388, 326, 652, 1304, 326, 652, 1021, 637, 1274, 2548, 212, 212, 1059, 2118, 3177, 492, 492, 809, 1618, 3236, 1040, 2080, 1043, 2086, 4172, 179, 179, 1022, 2044, 2044, 461, 1047, 2094, 1047, 961, 1922, 3844, 2883, 1037, 2074, 4148, 3111, 854, 1708, 2562, 972, 736, 736, 559, 1118, 2236, 1677, 490, 490, 241, 482, 723, 211, 422, 844, 633, 688, 1376, 688, 106, 106, 255, 510, 1020, 765, 823, 1646, 3292, 1646, 823, 1646, 3292, 2469, 767, 1534, 1534, 929, 1858, 3716, 929, 587, 1174, 1174, 690, 1380, 2760, 1380, 470, 940, 1880, 923, 1846, 3692, 923, 273, 546, 156, 1077, 2154, 3231, 781, 1562, 2343, 789, 1578, 3156, 789, 1033, 2066, 3099, 909, 1818, 687, 1374, 786, 1572, 786, 566, 456]
Distance matrix: {1: 1       0.000000
2      20.000000
3      24.083189
4      32.984845
5      32.984845
         ...
276    52.153619
277    42.755117
278    43.266615
279    34.409301
280    17.888544
Length: 280, dtype: float64, 2: 1      20.000000
2       0.000000
3      18.439089
4      34.176015
5      42.520583
         ...
276    54.405882
277    43.680659
278    36.221541
279    28.000000
280     8.944272
Length: 280, dtype: float64, 3: 1      24.083189
2      18.439089
3       0.000000
4      16.124515
5      27.784888
         ...
276    36.055513
277    25.298221
278    19.697716
279    10.770330
280    10.000000
Length: 280, dtype: float64, 4: 1      32.984845
2      34.176015
3      16.124515
4       0.000000
5      16.000000
         ...
276    20.396078
277    10.000000
278    16.492423
279    12.649111
280    25.298221
Length: 280, dtype: float64, 5: 1      32.984845
2      42.520583
3      27.784888
4      16.000000
5       0.000000
         ...
276    23.323808
277    18.867962
278    32.249031
279    28.284271
280    33.941125
Length: 280, dtype: float64, 6: 1      42.755117
2      50.477718
3      33.941125
4      18.867962
5      10.000000
         ...
276    15.620499
277    16.000000
278    32.557641
279    31.304952
280    41.617304
Length: 280, dtype: float64, 7: 1      55.713553
2      65.604878
3      49.517674
4      34.409301
5      23.323808
         ...
276    24.000000
277    29.732137
278    46.818800
279    46.647615
280    56.850682
Length: 280, dtype: float64, 8: 1      63.245553
2      72.111026
3      55.317267
4      39.597980
5      30.463092
         ...
276    25.298221
277    33.286634
278    50.119856
279    51.224994
280    63.245553
Length: 280, dtype: float64, 9: 1      61.188234
2      68.000000
3      50.477718
4      34.409301
5      28.284271
         ...
276    17.888544
277    26.907248
278    43.266615
279    45.254834
280    59.059292
Length: 280, dtype: float64, 10: 1      70.880181
2      78.892332
3      61.611687
4      45.607017
5      37.947332
         ...
276    28.844410
277    38.209946
278    54.405882
279    56.568542
280    69.971423
Length: 280, dtype: float64, 11: 1      78.587531
2      85.883642
3      68.264193
4      52.153619
5      45.607017
         ...
276    33.941125
277    44.045431
278    59.464275
279    62.481997
280    76.941536
Length: 280, dtype: float64, 12: 1      86.348133
2      93.037627
3      75.179785
4      59.059292
5      53.366656
         ...
276    40.000000
277    50.477718
278    65.115282
279    68.818602
280    84.095184
Length: 280, dtype: float64, 13: 1       94.148818
2      100.319490
3       82.292162
4       66.211781
5       61.188234
          ...
276     46.647615
277     57.306195
278     71.217975
279     75.471849
280     91.389277
Length: 280, dtype: float64, 14: 1      101.980390
2      107.703296
3       89.554453
4       73.539105
5       69.050706
          ...
276     53.665631
277     64.404969
278     77.665951
279     82.365041
280     98.792712
Length: 280, dtype: float64, 15: 1      92.779308
2      97.406365
3      79.120162
4      63.245553
5      60.133186
         ...
276    43.081318
277    53.851648
278    66.573268
279    71.554175
280    88.543774
Length: 280, dtype: float64, 16: 1      100.079968
2      101.271911
3       82.873397
4       68.117545
5       69.050706
          ...
276     48.000000
277     58.137767
278     67.052218
279     73.756356
280     92.779308
Length: 280, dtype: float64, 17: 1      116.068945
2      117.098249
3       98.731960
4       84.095184
5       84.852814
          ...
276     64.000000
277     74.108029
278     82.462113
279     89.442719
280    108.664622
Length: 280, dtype: float64, 18: 1      124.064499
2      125.027997
3      106.677083
4       92.086915
5       92.779308
          ...
276     72.000000
277     82.097503
278     90.244113
279     97.324200
280    116.619038
Length: 280, dtype: float64, 19: 1      132.060592
2      132.966161
3      114.629839
4      100.079968
5      100.717426
          ...
276     80.000000
277     90.088845
278     98.061205
279    105.223572
280    124.579292
Length: 280, dtype: float64, 20: 1      140.057131
2      140.911320
3      122.588743
4      108.074049
5      108.664622
          ...
276     88.000000
277     98.081599
278    105.905618
279    113.137085
280    132.544332
Length: 280, dtype: float64, 21: 1      148.054044
2      148.862353
3      130.552671
4      116.068945
5      116.619038
          ...
276     96.000000
277    106.075445
278    113.771701
279    121.061968
280    140.513345
Length: 280, dtype: float64, 22: 1      141.421356
2      145.602198
3      127.200629
4      111.570605
5      108.664622
          ...
276     91.214034
277    101.921538
278    112.924754
279    118.928550
280    136.821051
Length: 280, dtype: float64, 23: 1      125.602548
2      130.291980
3      111.946416
4       96.166522
5       92.779308
          ...
276     75.894664
277     86.648716
278     98.386991
279    104.000000
280    121.457812
Length: 280, dtype: float64, 24: 1      117.711512
2      122.702893
3      104.403065
4       88.543774
5       84.852814
          ...
276     68.352030
277     79.120162
278     91.301698
279     96.664368
280    113.841996
Length: 280, dtype: float64, 25: 1      133.506554
2      137.927517
3      119.549153
4      103.846040
5      100.717426
          ...
276     83.522452
277     94.254973
278    105.603030
279    111.427106
280    129.120099
Length: 280, dtype: float64, 26: 1      149.345238
2      153.310143
3      134.892550
4      119.331471
5      116.619038
          ...
276     98.954535
277    109.635761
278    120.332872
279    126.491106
280    144.554488
Length: 280, dtype: float64, 27: 1      157.276826
2      161.046577
3      142.618372
4      127.121989
5      124.579292
          ...
276    106.733313
277    117.388245
278    127.812362
279    134.104437
280    152.315462
Length: 280, dtype: float64, 28: 1      165.215011
2      168.807583
3      150.372870
4      134.937022
5      132.544332
          ...
276    114.542569
277    125.171882
278    135.351395
279    141.760361
280    160.099969
Length: 280, dtype: float64, 29: 1      172.418096
2      174.951422
3      156.524758
4      141.421356
5      140.057131
          ...
276    121.061968
277    131.529464
278    140.684043
279    147.512711
280    166.373075
Length: 280, dtype: float64, 30: 1      184.043473
2      185.558616
3      167.200478
4      152.472948
5      152.052622
          ...
276    132.242202
277    142.506140
278    150.625363
279    157.835357
280    177.132719
Length: 280, dtype: float64, 31: 1      184.390889
2      186.761880
3      168.344884
4      153.310143
5      152.052622
          ...
276    132.966161
277    143.401534
278    152.315462
279    159.248234
280    178.213355
Length: 280, dtype: float64, 32: 1      185.083765
2      188.297637
3      169.858765
4      154.557433
5      152.472948
          ...
276    134.164079
277    144.734239
278    154.402073
279    161.046577
280    179.644093
Length: 280, dtype: float64, 33: 1      198.645413
2      201.246118
3      182.822318
4      167.725967
5      166.192659
          ...
276    147.363496
277    157.835357
278    166.865215
279    173.769963
280    192.675894
Length: 280, dtype: float64, 34: 1      208.153789
2      209.876154
3      191.509791
4      176.725776
5      176.000000
          ...
276    156.460858
277    166.769302
278    174.951422
279    182.164761
280    201.434853
Length: 280, dtype: float64, 35: 1      224.142812
2      225.743217
3      207.393346
4      192.665513
5      192.000000
          ...
276    172.418096
277    182.701943
278    190.703959
279    197.989899
280    217.329243
Length: 280, dtype: float64, 36: 1      224.570702
2      226.874415
3      208.470621
4      193.494186
5      192.166594
          ...
276    173.158887
277    183.575598
278    192.208220
279    199.278699
280    218.357505
Length: 280, dtype: float64, 37: 1      232.860473
2      235.423024
3      217.006912
4      201.950489
5      200.359677
          ...
276    181.592951
277    192.052076
278    200.878072
279    207.884583
280    226.874415
Length: 280, dtype: float64, 38: 1      232.310138
2      234.196499
3      215.824002
4      200.997512
5      200.039996
          ...
276    180.709712
277    191.049732
278    199.278699
279    206.494552
280    225.743217
Length: 280, dtype: float64, 39: 1      232.034480
2      233.238076
3      214.932548
4      200.359677
5      200.039996
          ...
276    180.177690
277    190.378570
278    197.989899
279    205.406913
280    224.891085
Length: 280, dtype: float64, 40: 1      232.034480
2      232.551070
3      214.336185
4      200.039996
5      200.359677
          ...
276    180.000000
277    190.042101
278    197.017766
279    204.626489
280    224.321198
Length: 280, dtype: float64, 41: 1      232.310138
2      232.137890
3      214.037380
4      200.039996
5      200.997512
          ...
276    180.177690
277    190.042101
278    196.367003
279    204.156802
280    224.035711
Length: 280, dtype: float64, 42: 1      232.860473
2      232.000000
3      214.037380
4      200.359677
5      201.950489
          ...
276    180.709712
277    190.378570
278    196.040812
279    204.000000
280    224.035711
Length: 280, dtype: float64, 43: 1      233.683547
2      232.137890
3      214.336185
4      200.997512
5      203.214173
          ...
276    181.592951
277    191.049732
278    196.040812
279    204.156802
280    224.321198
Length: 280, dtype: float64, 44: 1      249.575640
2      248.128999
3      230.312831
4      216.923950
5      218.979451
          ...
276    197.463921
277    206.968597
278    212.037732
279    220.145406
280    240.299813
Length: 280, dtype: float64, 45: 1      248.805145
2      248.000000
3      230.034780
4      216.333077
5      217.807254
          ...
276    196.651977
277    206.349219
278    212.037732
279    220.000000
280    240.033331
Length: 280, dtype: float64, 46: 1      248.290153
2      248.128999
3      230.034780
4      216.037034
5      216.923950
          ...
276    196.163197
277    206.038831
278    212.339351
279    220.145406
280    240.033331
Length: 280, dtype: float64, 47: 1      248.032256
2      248.515593
3      230.312831
4      216.037034
5      216.333077
          ...
276    196.000000
277    206.038831
278    212.941306
279    220.581051
280    240.299813
Length: 280, dtype: float64, 48: 1      248.032256
2      249.158584
3      230.867928
4      216.333077
5      216.037034
          ...
276    196.163197
277    206.349219
278    213.841062
279    221.305219
280    240.831892
Length: 280, dtype: float64, 49: 1      248.290153
2      250.055994
3      231.698079
4      216.923950
5      216.037034
          ...
276    196.651977
277    206.968597
278    215.034881
279    222.315092
280    241.627813
Length: 280, dtype: float64, 50: 1      248.805145
2      251.205095
3      232.800344
4      217.807254
5      216.333077
          ...
276    197.463921
277    207.894204
278    216.517898
279    223.606798
280    242.684981
Length: 280, dtype: float64, 51: 1      256.780062
2      259.106156
3      240.707291
4      225.743217
5      224.321198
          ...
276    205.406913
277    215.824002
278    224.356859
279    231.482181
280    250.599282
Length: 280, dtype: float64, 52: 1      256.281096
2      257.992248
3      239.641399
4      224.891085
5      224.035711
          ...
276    204.626489
277    214.932548
278    222.925997
279    230.234663
280    249.575640
Length: 280, dtype: float64, 53: 1      256.031248
2      257.122539
3      238.838858
4      224.321198
5      224.035711
          ...
276    204.156802
277    214.336185
278    221.774660
279    229.259678
280    248.805145
Length: 280, dtype: float64, 54: 1      256.031248
2      256.499513
3      238.302329
4      224.035711
5      224.321198
          ...
276    204.000000
277    214.037380
278    220.907220
279    228.560714
280    248.290153
Length: 280, dtype: float64, 55: 1      256.281096
2      256.124969
3      238.033611
4      224.035711
5      224.891085
          ...
276    204.156802
277    214.037380
278    220.327030
279    228.140308
280    248.032256
Length: 280, dtype: float64, 56: 1      256.780062
2      256.000000
3      238.033611
4      224.321198
5      225.743217
          ...
276    204.626489
277    214.336185
278    220.036361
279    228.000000
280    248.032256
Length: 280, dtype: float64, 57: 1      257.526698
2      256.124969
3      238.302329
4      224.891085
5      226.874415
          ...
276    205.406913
277    214.932548
278    220.036361
279    228.140308
280    248.290153
Length: 280, dtype: float64, 58: 1      258.518858
2      256.499513
3      238.838858
4      225.743217
5      228.280529
          ...
276    206.494552
277    215.824002
278    220.327030
279    228.560714
280    248.805145
Length: 280, dtype: float64, 59: 1      250.599282
2      248.515593
3      230.867928
4      217.807254
5      220.435932
          ...
276    198.595065
277    207.894204
278    212.339351
279    220.581051
280    240.831892
Length: 280, dtype: float64, 60: 1      234.776489
2      232.551070
3      214.932548
4      201.950489
5      204.782812
          ...
276    182.822318
277    192.052076
278    196.367003
279    204.626489
280    224.891085
Length: 280, dtype: float64, 61: 1      236.135554
2      233.238076
3      215.824002
4      203.214173
5      206.649462
          ...
276    184.390889
277    193.380454
278    197.017766
279    205.406913
280    225.743217
Length: 280, dtype: float64, 62: 1      245.153013
2      241.867732
3      224.588513
4      212.198021
5      215.935175
          ...
276    193.545860
277    202.405534
278    205.650188
279    214.112120
280    234.478144
Length: 280, dtype: float64, 63: 1      252.990118
2      249.807926
3      232.499462
4      220.045450
5      223.651515
          ...
276    201.325607
277    210.237960
278    213.588389
279    222.036033
280    242.396370
Length: 280, dtype: float64, 64: 1      261.227870
2      257.992248
3      240.707291
4      228.280529
5      231.896529
          ...
276    209.570990
277    218.476543
278    221.774660
279    230.234663
280    250.599282
Length: 280, dtype: float64, 65: 1      262.937255
2      259.106156
3      242.033056
4      229.956518
5      234.093998
          ...
276    211.546685
277    220.227155
278    222.925997
279    231.482181
280    251.872984
Length: 280, dtype: float64, 66: 1      270.732340
2      267.013108
3      249.903982
4      237.756178
5      241.760212
          ...
276    219.271521
277    228.008772
278    230.824609
279    239.365829
280    259.753730
Length: 280, dtype: float64, 67: 1      276.925983
2      273.875884
3      256.538496
4      244.000000
5      247.386338
          ...
276    225.175487
277    234.170878
278    237.655212
279    246.089415
280    266.443240
Length: 280, dtype: float64, 68: 1      274.925444
2      272.734303
3      255.131339
4      242.123935
5      244.752937
          ...
276    222.925997
277    232.215417
278    236.541751
279    244.818300
280    265.088664
Length: 280, dtype: float64, 69: 1      282.842712
2      280.713377
3      263.096940
4      250.055994
5      252.602454
          ...
276    230.824609
277    240.141625
278    244.524027
279    252.792405
280    273.056771
Length: 280, dtype: float64, 70: 1      284.787640
2      281.822639
3      264.461717
4      251.872984
5      255.154855
          ...
276    232.997854
277    242.033056
278    245.601303
279    254.023621
280    274.372010
Length: 280, dtype: float64, 71: 1      286.356421
2      282.842712
3      265.668967
4      253.392975
5      257.153651
          ...
276    234.776489
277    243.614449
278    246.641440
279    255.154855
280    275.535842
Length: 280, dtype: float64, 72: 1      288.138855
2      284.084494
3      267.110464
4      255.154855
5      259.383885
          ...
276    236.812162
277    245.446532
278    247.935475
279    256.530700
280    276.925983
Length: 280, dtype: float64, 73: 1      290.131005
2      285.545093
3      268.782440
4      257.153651
5      261.839646
          ...
276    239.098306
277    247.523736
278    249.479458
279    258.147245
280    278.539046
Length: 280, dtype: float64, 74: 1      292.328582
2      287.221169
3      270.680624
4      259.383885
5      264.514650
          ...
276    241.627813
277    249.839949
278    251.268780
279    260.000000
280    280.371183
Length: 280, dtype: float64, 75: 1      294.726992
2      289.108976
3      272.800293
4      261.839646
5      267.402319
          ...
276    244.393126
277    252.388589
278    253.298243
279    262.083956
280    282.418130
Length: 280, dtype: float64, 76: 1      287.137598
2      281.368086
3      265.126385
4      254.275441